### ISSUE TITLE
[new app] Meditation App for Remarkable Tablet

### ISSUE THREAD

**Issue by garyzhuge** [rmkit-dev/rmkit#1]
Hi, 
Thanks for creating this framework! I am interested in porting this animation onto my remarkable as well as adding a timer for a meditation app for an animation app. However, how would I create the expanding and contracting animation effect? Looking at the documentation could you potentially chain draw_bitmap with a 3-second delay of pictures of different sizes? Or is there a better way to do it?
![animation](https://user-images.githubusercontent.com/32006095/91609433-6d0ff900-e945-11ea-8787-1665caef0a48.gif)

**Comment by okayzed** [comment]
You can try the draw_bitmap approach, i'd like to see if it works! I think you can get a smooth animation if you  call draw_circle and progressively expand a circle or otherwise draw something simpler. I will try out animating a simple image, as well and post back with results.

**Comment by garyzhuge** [comment]
Also what is the .cpy file format? This code is c++ right?

**Comment by okayzed** [comment]
https://github.com/raisjn/okp/blob/master/USAGE.md

yes, this is C++. cpy is semantic sugar on top of C++, okp is a pre-processor that translates .cpy files to .cpp and compiles them

you'll need to `pip install okp` (and have gcc as well as the cross compiler for ARM), but that's about it, iirc

**Comment by okayzed** [comment]
```
#include <cstddef>
#include "../build/rmkit.h"
#include "assets.h"
#include <unistd.h>
using namespace std

class Animation : public ui::Widget:
  public:
  shared_ptr<ui::Pixmap> img
  int mx, my
  Animation(int x, y, w, h) : ui::Widget(x, y, w, h):
    self.mx = self.x + self.w / 2
    self.my = self.x + self.h / 2

  void animate():
    static int size = 100;
    static int dir = 1
    static int offset = 0
    self.img = make_shared<ui::Pixmap>(self.mx - offset, self.my - offset, size, size, ICON(assets::flag_solid_png))

    offset += (dir * 5)
    size += 10 * dir;
    if size >= 200 || size <= 100:
      dir *= -1;

    ui::TaskQueue::add_task([=]() {
      self.animate()
      usleep(1000 * 200)
    })

  void render():
    if self.img != nullptr:
      self.fb->draw_rect(self.x, self.y, self.w, self.h, WHITE, 1)
      self.img->render()

class CircleAnimation : public ui::Widget:
  public:
  int size = 1
  int color = BLACK
  shared_ptr<ui::Pixmap> img
  CircleAnimation(int x, y, w, h) : ui::Widget(x, y, w, h):
    pass

  void animate():
    static int dir = 1

    size += 1 * dir;
    if size >= 200:
      size = 0
      if color == BLACK:
        color = WHITE
      else:
        color = BLACK

    ui::TaskQueue::add_task([=]() {
      self.animate()
      ui::MainLoop::refresh()
      usleep(1000 * 50)
    })

  void render():
    self.fb->draw_circle(self.x+self.w/2, self.y+self.h/2, self.size, 1, self.color, 0 /* fill */)

class App:
  public:
  ui::Scene demo_scene


  App():
    demo_scene = ui::make_scene()
    ui::MainLoop::set_scene(demo_scene)
    fb := framebuffer::get()
    fb->clear_screen()
    fb->redraw_screen()
    fw, fh := fb->get_display_size()

    a := new CircleAnimation(fw/2, fh/2, 1, 1)
    demo_scene->add(a)
    a->animate()

//    b := new Animation(200, 200, 200, 200)
//    demo_scene->add(b)
//    b->animate()




  def handle_key_event(input::SynKeyEvent &key_ev):
    print "KEY PRESSED", key_ev.key

  def handle_motion_event(input::SynMouseEvent &syn_ev):
    pass

  def run():
    ui::MainLoop::key_event += PLS_DELEGATE(self.handle_key_event)
    ui::MainLoop::motion_event += PLS_DELEGATE(self.handle_motion_event)

    // just to kick off the app, we do a full redraw
    ui::MainLoop::refresh()
    ui::MainLoop::redraw()
    while true:
      ui::MainLoop::main()
      ui::MainLoop::refresh()
      ui::MainLoop::redraw()
      ui::MainLoop::read_input()


def main():
  App app
  app.run()
```

i included a animation of image and animation by drawing circles. the image animation is not so great, but circle animation is fine. if you get it running, make sure to run `top` on the remarkable to see how its doing on CPU

**Comment by okayzed** [comment]
by the way, another conllaborator mentioned that you don't need to use cpy - you can use rmkit.h as a single file you include in a cpp project

**Comment by raisjnn** [comment]
it would be interesting to finish the animation_demo that's checked in and package it in toltec, maybe adding a timer or breathing exercises.
