### ISSUE TITLE
remux not working with 2.6.1.71

### ISSUE THREAD

**Issue by Jab2870** [rmkit-dev/rmkit#117]
I upgraded my RM2 to the latest software version and remux has stopped working.

I initially noticed that for some reason the systemd unit was no longer in the
path /lib/systemd/system so for good measure I uninstalled and reinstalled remux
using opkg.

Once re-installed, I re-enabled the systemd unit and rebooted the device.

I am still not able to swipe up on either edge to start the launcher.

Do you have any suggestions?

**Comment by Eeems** [comment]
rm2fb doesn't work with the latest release yet. Most applications wont either due to various system changes that haven't been taken into account yet.

We also don't have an updated toolchain to work with.

**Comment by Jab2870** [comment]
Thanks for the quick reply.

I'll wait then, that's fine.

**Comment by raisjn** [comment]
yes, what eeems said is correct, but regarding your situation in specific: it is better to re-run the toltec bootstrap or toltec re-enable script, as you only re-installed remux but did not reinstall rm2fb. i would not suggest installing rm2fb yet, but once rm2fb support for xochitl 2.6 lands, i can ping you here

re: rm2fb: we have updated code that works with xochitl 2.6, just need to push it to rm2fb, then push to toltec testing (within the next few days), then stable merge (next week)

**Comment by raisjn** [comment]
https://github.com/toltec-dev/toltec/pull/301 is the toltec pull (can get the .ipk from the build artifacts on it)

**Comment by raisjn** [comment]
this is now in stable, afaict: https://toltec-dev.org/stable/ - please upgrade when convenient. i'll leave this issue open a few more days

**Comment by mehalter** [comment]
I'm having some issues with the latest `rm2fb` package where `remux` is saying that I don't have it installed and it is not functioning with the 2 finger swipe up. Could this be a result of the new update to rm2fb or something that needs to be updated in remux? For reference I'm also able to successfully use [remarkable_mouse](https://github.com/Evidlo/remarkable_mouse) that relies on rm2fb as well as ddvk's remarkable-hacks (unsure if this relies on rm2fb to function) as I was before the 2.6 update.

**Comment by raisjn** [comment]
if you did an update, you need to run the toltec reenable script or rerun the bootstrap because the system partition is replaced on every update. 

also make sure to update to rm2fb 1.0.1

**Comment by raisjn** [comment]
also, maybe reboot

**Comment by mehalter** [comment]
I tried this process and rebooting. Once the issues persisted I went ahead and removed all of the modifications entirely and started from scratch reinstalling toltec and then simply just doing `rm2fb` and `remux` and have the same issues (all of these with reboots in between to be safe)

**Comment by raisjn** [comment]
i haven't installed 2.6 yet, but will update and look into it. what is in `journalctl -u rm2fb`? anything that looks like errors?

**Comment by raisjn** [comment]
i installed 2.6 and then ran the re-enable scripts. several packages were re-installed (including rm2fb and remux) and things worked. i then deleted my ~/.entware and unmounted /opt and then deleted /opt as well and re-installed toltec. i then installed rm2fb, remux & koreader and it worked as well. please make sure you are on stable and the version of rm2fb is 1.0.0-8 or 1.0.1 (or higher)


![version](https://user-images.githubusercontent.com/70462544/113380314-b9cf0e80-9330-11eb-9c9d-daf504b0d844.png)
![remux](https://user-images.githubusercontent.com/70462544/113380313-b89de180-9330-11eb-8b48-9dcd1e77d98c.png)

**Comment by mehalter** [comment]
Ah after some debugging I found that it's an issue I think with the default swipe gestures that got set up on my remarkable. It looks like without a `remux.conf` file the default gestures don't specify a number of fingers and it's never getting triggered by my swiping:

```
SETTING LAUNCH GESTURES TO DEFAULT
ADDED SWIPE GESTURE:
  command: 
  gesture: swipe
  fingers: 
  min_events: 
  zone: 0 0 140 1872
  direction: up
ADDED SWIPE GESTURE:
  command: 
  gesture: swipe
  fingers: 
  min_events: 
  zone: 1263 0 1404 1872
  direction: up
  ```
