### ISSUE TITLE
[remux] start an application in the background

### ISSUE THREAD

**Issue by AnyTimeTraveler** [rmkit-dev/rmkit#118]
I'd like to start my app ([pipes-and-rust](https://github.com/AnyTimeTraveler/pipes-and-rust)) in the background and continue running whatever application was running before.
I have looked over the code and sadly don't understand what it is doing, as I don't know CPython.
While I can get the gist of what it's doing, I don't exactly see where and how the process control happens.

My question:
Is it possible to create a script that is launched by remux, which then spawns a background process that is not stopped when the user switches to another app?

**Comment by raisjn** [comment]
yes, it is possible. cpy is just syntactic sugar on top of cpp, so if you know cpp, then you can write cpy. 

regarding how to make a background process: remux uses process groups to start/stop the processes it launched (and to catch children of launched processes, like apps launched from scripts). if you want to make a backgrounded app that can't be stopped by remux, then you can launch it in its own process group (that is different from its parent). you can usually use `setsid` command to do this but there are other ways. 

the issue with this is that remux will not be able to kill your program. (just as an FYI). so maybe you write a second script that can kill your app

**Comment by raisjn** [comment]
process control code: 
some code pointers, if you are interested:

https://github.com/rmkit-dev/rmkit/blob/master/src/remux/launcher.cpy#L493
https://github.com/rmkit-dev/rmkit/blob/master/src/remux/launcher.cpy#L630
https://github.com/rmkit-dev/rmkit/blob/master/src/shared/proc.cpy#L155

**Comment by raisjn** [comment]
#resolved
