### ISSUE TITLE
[remux][doc ?] How to stop apps with remux ?

### ISSUE THREAD

**Issue by Baccanno** [rmkit-dev/rmkit#119]
It's all in the title :)
Thanks for the app
Best

**Comment by raisjn** [comment]
if the app is running, its mem usage should show up or it will say '?MB' to the right of the app name. you can click that to kill an app. if you just want to pause an app, whenever you launch remux and switch apps, the other apps will be paused. 

generally, there is no need to kill an app unless you really want to restart it. (xochitl is not killable unless you are on a newer build)

**Comment by Baccanno** [comment]
Thank you very much it works :)
I like to have only the minimum alive at a time.
