### ISSUE TITLE
[remux] self closing menu

### ISSUE THREAD

**Issue by Pemo11235** [rmkit-dev/rmkit#125]
Via toltec testing , remux and display/rm2fb .

 When I swipe to open the menu with default gesture, It shows for a second the remux's menu and It self closing immediately .

 It happens in xochitl , and other apps too (koreader, nao, etc) .

Not sure what trigger the issue and how to reproduce it

Thanks :)

**Comment by raisjn** [comment]
do you have genie also running or another instance of remux ?

**Comment by Pemo11235** [comment]
`systemctl status ` returns a `genie.service` and `remux.service` running

**Comment by raisjn** [comment]
Is possible they are both setup to launch remux. Make sure only one is launching remux

**Comment by Pemo11235** [comment]
I solved t : in `/home/root/.config/remux/remux.conf`, set `launch_gesture=`  , as doc suggest.

My only doubt is that in my genie confing there's no remux's launch or gesture related to.  Am I missed something?

**Comment by raisjn** [comment]
maybe the genie service is old and on old config
