### ISSUE TITLE
What is the justification behind half the codebase being written in COBOL?

### ISSUE THREAD

**Issue by AceofShovels** [rmkit-dev/rmkit#126]
I get cpp for performance, but why COBOL of all the options?

**Comment by Eeems** [comment]
It's written in cpp, but just using a dialect similar to python: https://github.com/raisjn/okp

**Comment by raisjn** [comment]
> I get cpp for performance, but why COBOL of all the options?

what are you thinking of building? its just cpp everywhere, sometimes with sugar

**Comment by AceofShovels** [comment]
Ah I see. I've never seen that language before, and github recognizes the .cpy files as COBOL
