### ISSUE TITLE
[remux] xochitl is not started for new rm2fb version in toltec

### ISSUE THREAD

**Issue by JanLuca** [rmkit-dev/rmkit#127]
`proc.list_procs` uses the program name defined in `/proc/<id>/stat` to build up its process list. This causes the problem that it does not account that programs changed their argv[0] to be listed by a different cmdline.

Particularity, this behavior causes the problem that `remux` is not compatible with the new rm2fb version released on toltec for the update 2.6+ since `rm2fb-server` now uses `xochitl` instead of `remarkable-shutdown` [1]. To avoid the problem that it is listed by the wrong name it changes the cmdline to `rm2fb-server` [1] so that `/proc/<id>/cmdline` contains correctly `rm2fb-server` but since the underlying exe is `xochitl` the second value of `/proc/<id>/stat` is `(xochitl)`.

This way `remux` assumes that `xochitl --system` is already started which is not correct.

I would either suggest to include a check in the process list code if the cmdline and stat differs or depend on `systemctl start/stop  xochitl` to handle the execution and state of `xochitl`. 

[1] https://github.com/toltec-dev/toltec/commit/12e6fb4b419ff8af189f7b96e4e5f18dde6d1c55

**Comment by raisjn** [comment]
thanks for investigating! I thought this was fixed

cc @matteodelabre

**Comment by JanLuca** [comment]
I think https://github.com/toltec-dev/toltec/commit/12e6fb4b419ff8af189f7b96e4e5f18dde6d1c55 already includes a patch but this just changes cmdline. The problem is that according to `man 5 proc` the second field is always the name of the executable.

But I just tested it: The problem can be fixed by creating a symlink to `/usr/bin/xochitl` and call this. Then the exec name is correct in stat as well

**Comment by raisjn** [comment]
regarding using systemd: the default xochitl.service has a watchdog which will restart the process if it doesn't ping every X minutes. this interferes with backgrounding xochitl. since I want to leave the system service mostly unmodified, remux behaves the way it does

for the symlink: is Toltec or rm2fb a good place to put a PR?

for stat vs cmdline: can remux switch to cmdline and things would work?

**Comment by JanLuca** [comment]
I just try to solve this using a symlink and if this works I open a PR on toltec

**Comment by JanLuca** [comment]
Ok, the name in `/proc/<id>/stat` is not the problem. The problem is in the function `check_args`. It returns true if somewhere in a path is the name of argument. For example it returns true for the cmdline `inotifywait -m -q --format %f -e DELETE /home/root/.local/share/remarkable/xochitl` where the name is just the name of the data dir.

**Comment by matteodelabre** [comment]
I think this can be closed, since the issue has been fixed in toltec-dev/toltec#363.
