### ISSUE TITLE
[website] Expired certificates

### ISSUE THREAD

**Issue by RaelZero** [rmkit-dev/rmkit#129]
Heyo!

Just FYI - SSL certificates have expried on https://rmkit.dev/ and HSTS is enabled, meaning the website is inaccessible.

Maybe something went wrong with your `certbot renew`? 

And congratulations and thanks for all the good work!

**Comment by raisjn** [comment]
thank you, should be fixed now

**Comment by Eeems** [comment]
Can confirm, the cert is valid on my end now.

**Comment by RaelZero** [comment]
Cheers, mate! Closing issue.
