### ISSUE TITLE
[rpncalc] Input on subsequent calculations doesn't push the stack first

### ISSUE THREAD

**Issue by Snowflake6** [rmkit-dev/rmkit#139]
Desired behaviour:

6 9 [push]
2 3 [ * ]  -> returns 1587. to stack.
4 [ * ]  -> returns 6348. to stack.

What happens:

6 9 [push]
2 3 [ * ]  -> returns 1587. to stack.
4  ->  adds the 4 to 1587. to show "1587.4".

On the HP RPN calculators i've used, when there is a number on the stack, entering another number automatically "push"es the value to make room for it.

**Comment by raisjn** [comment]
which operations should this happen for? https://github.com/rmkit-dev/rmkit/pull/140 is a first take at it, you can download the binaries off the PR artifacts.

**Comment by torwag** [comment]
basically for all operations ;)
On HP the result is basically always displayed on stack 1.
That is, that you can perform other calculations subsequently in one go
E.g.
6 9 [push]
2 3 [ * ] -> returns 1587. to stack.

2 3 [ push ]
6 9 [ * ] -> returns again 1587 in stack 1 first result is now in stack 2
[ - ] -> returns 0 in stack 1 as it is stack 2 - stack 1.

**Comment by raisjn** [comment]
this is now pushed and you can get the build off build.rmkit.dev
