### ISSUE TITLE
rmkit.dev expired certificate

### ISSUE THREAD

**Issue by HalosGhost** [rmkit-dev/rmkit#145]
@raisjn it looks like the cert has expired, but the server sets HSTS, so the site is fully inaccessible to browsers that respect HSTS. (similar to #137 it seems)

**Comment by raisjn** [comment]
thanks! i restarted nginx and it's fixed (i think). that's the key step i keep missing when i renew

**Comment by Eeems** [comment]
Looks fixed to me now.

**Comment by HalosGhost** [comment]
@Eeems indeed; all is well! Thanks @raisjn!
