### ISSUE TITLE
[minesweeper] flags don't show up

### ISSUE THREAD

**Issue by RedshiftVelocities** [rmkit-dev/rmkit#147]
In this picture, the square in the center of all the ones should be flagged. When I try to flag it, the outline disappears, but no flag appears. Thanks for any help you can offer.
![no-flags](https://user-images.githubusercontent.com/43499473/136679631-065c63e5-425b-44a0-919f-1e20408d6cd2.jpg)
.

**Comment by raisjn** [comment]
thanks for the report! i'm not sure what is happening, i will look into it. you can try minesweeper game from the `puzzles` package in toltec in the  meantime

**Comment by Hafting** [comment]
I see this problem too – no flags, just white area. This is on a remarkable2, could that be a problem?

**Comment by raisjn** [comment]
i have pushed a commit that should fix this. it was introduced in 47ec819 (yay git bisect) and fixed in cc1dfe4. i still recommend using mines from the `puzzles` package, though

you can get the updated binary from https://build.rmkit.dev/master/latest/files/
