### ISSUE TITLE
I'm struggling to get iago to work

### ISSUE THREAD

**Issue by Cindy-Jie-01** [rmkit-dev/rmkit#148]
I have installed iago, lamp, and genie via toltec and also created a config file genie.conf in the file following the read.me file, but three finger swipe down is not triggering iago

**Comment by Cindy-Jie-01** [comment]
I now got it to work, but a lot of weird flickering is happening. Like old displays are flickering in over the new ones and such

**Comment by raisjn** [comment]
maybe genie or iago is running twice?
