### ISSUE TITLE
Cant open iago with genie

### ISSUE THREAD

**Issue by Frixon21** [rmkit-dev/rmkit#151]
I can't seem to open it, it was working fine on version 2.10.1, but when I updated it to 2.10.2 (had to reinstall everything) it stopped working.

**Comment by raisjn** [comment]
i think it might be ddvk/remarkable2-framebuffer#18, you might need new signatures for the updated version. try checking the logs of rm2fb (`journalctl -u rm2fb` or similar)

**Comment by Frixon21** [comment]
They are empty, not sure if that's good or bad

**Comment by Frixon21** [comment]
I can seem to find rm2fb.conf 
`reMarkable: // opkg files rm2fb-client`
`Package rm2fb-client (1:0.0.8-2) is installed on root and has the following files:`
```
/opt/lib/librm2fb_client.so.1.0
/etc/systemd/system/remux.service.d/rm2fb-preload.conf
/opt/bin/rm2fb-client
/etc/systemd/system/draft.service.d/rm2fb-preload.conf
/usr/lib/librm2fb_client.so.1.0
/opt/etc/xochitl.env.d/rm2fb-preload.env
/etc/systemd/system/tarnish.service.d/rm2fb-preload.conf
/usr/lib/librm2fb_client.so.1.0.1
/usr/lib/librm2fb_client.so.1
/opt/lib/librm2fb_client.so.1
/opt/lib/librm2fb_client.so.1.0.1
```
I've reinstalled rm2fb using toltec but that still doesn't fix it. Any ideas?

**Comment by Eeems** [comment]
> 
> 
> I can seem to find rm2fb.conf `reMarkable: // opkg files rm2fb-client` `Package rm2fb-client (1:0.0.8-2) is installed on root and has the following files:`
> 
> ```
> /opt/lib/librm2fb_client.so.1.0
> /etc/systemd/system/remux.service.d/rm2fb-preload.conf
> /opt/bin/rm2fb-client
> /etc/systemd/system/draft.service.d/rm2fb-preload.conf
> /usr/lib/librm2fb_client.so.1.0
> /opt/etc/xochitl.env.d/rm2fb-preload.env
> /etc/systemd/system/tarnish.service.d/rm2fb-preload.conf
> /usr/lib/librm2fb_client.so.1.0.1
> /usr/lib/librm2fb_client.so.1
> /opt/lib/librm2fb_client.so.1
> /opt/lib/librm2fb_client.so.1.0.1
> ```
> 
> I've reinstalled rm2fb using toltec but that still doesn't fix it. Any ideas?

It's part of the `display` package.

**Comment by Frixon21** [comment]
It showed the display package as empty so I went ahead and uninstalled everything and reinstalled it. I still cant find it
This is what I get with the display package:
```
reMarkable: ~/ opkg files display
Package display (1:0.0.8-2) is installed on root and has the following files:
/opt/lib/librm2fb_server.so.1.0.1
/lib/systemd/system/rm2fb.service
/opt/lib/librm2fb_server.so.1.0
/opt/lib/librm2fb_server.so.1
```

**Comment by Eeems** [comment]
What do you mean you can't find it? I'm seeing rm2fb in the output of `opkg files display` that you provided. Do you mean that there are no logs for the service? Have you checked `systemctl status rm2fb` to make sure it's enabled/running?

**Comment by Frixon21** [comment]
Sorry, I'm pretty new to this, I was looking for the .config file since I thought that's what I needed my bad. Doing a `systemctl status rm2fb` I get this:
```
[[0;1;31m●[[0m rm2fb.service - reMarkable 2 Framebuffer Server
     Loaded: loaded (/lib/systemd/system/rm2fb.service; enabled; vendor preset: disabled)
     Active: [[0;1;31mfailed[[0m (Result: exit-code) since Mon 2021-11-01 18:36:27 UTC; 15s ago
    Process: 1068 ExecStart=/usr/bin/xochitl [[0;1;31m(code=exited, status=255/EXCEPTION)[[0m
   Main PID: 1068 (code=exited, status=255/EXCEPTION)

Nov 01 18:36:27 reMarkable systemd[1]: rm2fb.service: Scheduled restart job, restart counter is at 5.
Nov 01 18:36:27 reMarkable systemd[1]: Stopped reMarkable 2 Framebuffer Server.
Nov 01 18:36:27 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mrm2fb.service: Start request repeated too quickly.[[0m
Nov 01 18:36:27 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mrm2fb.service: Failed with result 'exit-code'.[[0m
Nov 01 18:36:27 reMarkable systemd[1]: [[0;1;31m[[0;1;39m[[0;1;31mFailed to start reMarkable 2 Framebuffer Server.[[0m
```

**Comment by Eeems** [comment]
So it's failing to start, likely because you don't have the updated signatures as @raisjn mentioned. You'll need to create the `/etc/rm2fb.conf` file and populate it with the signature configuration. Toltec doesn't ship the package with the configuration file and instead relies on the default configuration built into rm2fb.

**Comment by Frixon21** [comment]
Thank you! I did what you said and it finally works!
