### ISSUE TITLE
Remux menu won't stay open after swipe

### ISSUE THREAD

**Issue by bkirwi** [rmkit-dev/rmkit#154]
I took a video of the issue this morning... low quality, but should be enough to get the idea:

https://user-images.githubusercontent.com/1596339/141693653-59f391f7-c252-4e41-9bda-c44b49e35efa.mov

Other info that might be useful:
- Running remarkable 2, xochitl 2.8, the latest testing-branch toltec releases. I can't recall when it started; it's been happening quite regularly for a month or two, but I don't remember it happening at all in the first half of the year.
- The issue is sporadic. It'll sometimes work correctly dozens of times over a couple days, and others it seems to happen every time I want to pull up the menu. In the video it takes three tries for it to work correctly, but I've seen up to ~20.
- I have the swipe on the other edge configured as the "back gesture" and it works perfectly even when the menu is glitching.
- It might not be obvious from the video, but when the menu disappears it leaves some artifacts behind, both where the menu is drawn and in the upper-left corner.
- The first swipe or two after a restart always seem to work properly. (But the issue will still appear even if I havent started any apps other than xochitl.)

`journal -xe` output from a failed attempt:

```
Nov 14 14:18:18 reMarkable remux[19732]: CURRENT APP IS Remarkable
Nov 14 14:18:18 reMarkable remux[19732]: current app 0.00878336
Nov 14 14:18:18 reMarkable remux[19732]: SENDING 19 TO GROUP -19746 RET 0
Nov 14 14:18:18 reMarkable remux[19732]: term apps 0.00669256
Nov 14 14:18:18 reMarkable remux[19732]: SNAPSHOTTING Remarkable
Nov 14 14:18:19 reMarkable remux[19732]: No such file or directory
Nov 14 14:18:19 reMarkable remux[19732]: RENDERING Remarkable
Nov 14 14:18:19 reMarkable remux[19732]: RENDERING Remarkable
Nov 14 14:18:19 reMarkable remux[19732]: LAUNCHING APP Remarkable Remarkable
Nov 14 14:18:19 reMarkable remux[19732]: RESETTING MT GESTURES
Nov 14 14:18:19 reMarkable remux[19732]: XOCHITL CMD IS /opt/bin/xochitl --system
Nov 14 14:18:19 reMarkable remux[19732]: CHECKING PROCESS xochitl 1
Nov 14 14:18:19 reMarkable remux[19732]: xochitl IS ALREADY RUNNING, RESUMING
Nov 14 14:18:19 reMarkable remux[19732]: SENDING 18 TO GROUP -19746 RET 0
Nov 14 14:18:19 reMarkable remux[19732]: RENDERING Remarkable
Nov 14 14:18:19 reMarkable remux[19732]: LAUNCHING APP Remarkable Remarkable
Nov 14 14:18:19 reMarkable remux[19732]: RESETTING MT GESTURES
Nov 14 14:18:19 reMarkable remux[19732]: XOCHITL CMD IS /opt/bin/xochitl --system
Nov 14 14:18:19 reMarkable remux[19732]: CHECKING PROCESS xochitl 1
Nov 14 14:18:19 reMarkable remux[19732]: xochitl IS ALREADY RUNNING, RESUMING
Nov 14 14:18:19 reMarkable remux[19732]: SENDING 18 TO GROUP -19746 RET 0
Nov 14 14:18:19 reMarkable remux[19732]: RENDERING Remarkable
```

**Comment by raisjn** [comment]
thank you for reporting! i've seen sporadic reports of this. as a workaround, i added some code to not hide the launcher within 500ms of it being shown, if you want to test it out: https://raisjn.net/remux.min_display_time 

```
commit b6b86a464774c699e265c0b3cc71933db5af65bb
Author: okay <okay@arkose>
Date:   Sun Nov 14 12:12:28 2021 -0800

    [remux] launcher must be visible for at least 500ms before hiding
    
    this is to prevent the launch / hide behavior bkirwi has been seeing

diff --git a/src/remux/launcher.cpy b/src/remux/launcher.cpy
index 10fda67..418fe2e 100644
--- a/src/remux/launcher.cpy
+++ b/src/remux/launcher.cpy
@@ -34,6 +34,8 @@ DIALOG_HEIGHT := 800
 LAST_ACTION := 0
 USE_KOREADER_WORKAROUND := false
 
+MIN_DISPLAY_TIME := 500
+
 string CURRENT_APP = "_"
 string NAO_BIN="/opt/bin/nao"
 
@@ -239,6 +241,7 @@ class App: public IApp:
   input_event *touch_flood
   input_event *button_flood
   vector<input::TouchEvent> touch_events
+  std::chrono::system_clock::time_point last_display_time
 
   static int lastpress = RAND_MAX
   static int event_press_id = 0
@@ -265,6 +268,14 @@ class App: public IApp:
     get_current_app()
 
     app_dialog->on_hide += PLS_LAMBDA(auto &d):
+      now := std::chrono::system_clock::now();
+      int_ms := std::chrono::duration_cast<std::chrono::milliseconds>(now - last_display_time);
+
+      debug "DISPLAYED LAUNCHER FOR", int_ms.count(), "MS"
+      if int_ms.count() < MIN_DISPLAY_TIME:
+        debug "NOT HIDING LAUNCHER BECAUSE INTERVAL < ", MIN_DISPLAY_TIME
+        return
+
       self.render_bg()
       launch(CURRENT_APP)
       // we put the unmonitor in a timeout to prevent
@@ -447,6 +458,8 @@ class App: public IApp:
     if ui::MainLoop::overlay_is_visible:
       return
 
+    last_display_time = std::chrono::system_clock::now();
+
     ui::MainLoop::in.monitor(ui::MainLoop::in.wacom.fd)
     ClockWatch cz
 
```

**Comment by bkirwi** [comment]
Been running the test build for the last few days, and things do seem much better! I haven't been able to reproduce the issue since.

One surprising thing is that when I try and manually trigger the code you've added -- by swiping and then immediately tapping -- I'm able to trigger the `NOT HIDING LAUNCHER` log message, but the menu is still dismissed. This isn't _bad_ behaviour, really, but it's weird that hitting that codepath doesn't always prevent the menu from being dismissed. Also interesting that it always displays twice, normally with slightly different timestamps:

```
Nov 18 15:51:27 reMarkable remux[22598]: DISPLAYED LAUNCHER FOR 363 MS
Nov 18 15:51:27 reMarkable remux[22598]: NOT HIDING LAUNCHER BECAUSE INTERVAL <  500
Nov 18 15:51:27 reMarkable remux[22598]: DISPLAYED LAUNCHER FOR 366 MS
Nov 18 15:51:27 reMarkable remux[22598]: NOT HIDING LAUNCHER BECAUSE INTERVAL <  500
```

But anyways - my experience has been lots better, and it's hard to imagine this logic doing any harm, so +1 to rolling forward with this. I'll follow up here if I notice anything else interesting!

**Comment by raisjn** [comment]
closing out since this is now in stable
