### ISSUE TITLE
[remux] Wifi not working after sleep

### ISSUE THREAD

**Issue by mariusdkm** [rmkit-dev/rmkit#157]
After installing remux through toltec, the wifi wouldn't work after waking the tablet after a "longer" sleep(probably like >5 min). 
 
Only a restart of the rm solved solved the wifi issue, just a restart of `xochitl` didn't do anything(also just re- and disabling the wifi though the gui didn't do anything).
I have a remarkable 2 with Software version 2.10.3.379, where `rm2fb-client` and `display` packages from the stable toltec branch aren't supported yet,  because of that I installed everything (also remux) from the testing branch. I should note, that I also have ddvk-hacks installed.

So I had installed:
* remux - 0.1.11-1
* rm2fb-client - 0.0.10-1
* display - 0.0.10-1
* ddvk-hacks - 26.02-1

Uninstalling remux solved the wifi issue.  

I also noticed, that Issue #156 also has some noted some wifi issues

**Comment by Eeems** [comment]
Do you have rm2-suspend-fix installed?

**Comment by mariusdkm** [comment]
No, what does that do?

**Comment by Eeems** [comment]
https://github.com/toltec-dev/toltec/blob/stable/package/rm2-suspend-fix/rm2-suspend-fix.sh

It tries to resolve issues with suspend and wifi. Could you install and see if it resolves the issue for you?

**Comment by raisjn** [comment]
remux had some logic to reload the wifi driver after resume, I wonder if the driver name changed or if more drivers are being used

**Comment by mariusdkm** [comment]
I think installing `rm2-suspend-fix` fixes it.
If the wifi issue arises again, I will reopen this issue

**Comment by Eeems** [comment]
> remux had some logic to reload the wifi driver after resume, I wonder if the driver name changed or if more drivers are being used

It might be a timing issue as well.
