### ISSUE TITLE
[ Remux ] Works randomly but most often the menu doesn't show

### ISSUE THREAD

**Issue by mass-im** [rmkit-dev/rmkit#159]
Hi,

I was wondering how I could debug this properly.
I'm having issues with the appearance of the menu. Most of the times it simply doesn't show when I swipe.
Didn't add any specific configuration or other apps and I'm using the rm2.
Checking the status using `systemctl status remux` doesn't really show anything wrong, all actually looks pretty good.
But from this point I don't know how to debug.
Any tips?

Thanks in advance!

**Comment by raisjn** [comment]
1. try swiping with four fingers to clear the touch buffers
2. are you holding a stylus while swiping?
3. the swipe should be 50% of the screen

**Comment by raisjn** [comment]
you can run "echo show > /run/remux.api" from command line to force it to show - that should help hopefully.

https://imgur.com/a/rT94L8W is what the swipe should look like

**Comment by mass-im** [comment]
Thanks for this! It was not clear to me the gesture should cover 50% of the screen.
