### ISSUE TITLE
[remux] proposal: keep the menu in one page, if possible

### ISSUE THREAD

**Issue by Hafting** [rmkit-dev/rmkit#162]
I have so many toltec apps, so remux uses two pages for the menu. But there is plenty of space on the remarkable screen, room for many more lines.
Going from page to page in the menu is unwanted extra work – it'd be nicer if the menu simply was longer, up to the height of the screen if needed.

**Comment by raisjn** [comment]
Thanks for the idea! (and I'm glad you have so many apps :) ) For now, feel free to re-compile remux with an appropriate height: https://github.com/rmkit-dev/rmkit/blob/master/src/remux/launcher.cpy#L266. If you need help with compiling, let me know - there is a doc in docs/ about compiling under different platforms.  

Long term - we can make an option in the remux config file to grow in size (or allow configurable height), should be reasonably easy - just need to read the custom height from config file and then instantiate the dialog with it.  Auto-growing may be a little more work

**Comment by raisjn** [comment]
the latest build of remux on https://build.rmkit.dev/master/latest/rm supports config options `dialog_height` and `dialog_width` in remux.conf (see remux's README.md for more info). added in https://github.com/rmkit-dev/rmkit/commit/deb3a610a23ab66723b5e497905495cc5bcd1464

**Comment by raisjn** [comment]
this is in PR https://github.com/toltec-dev/toltec/pull/542, i'll close this task out when it gets merged into stable
