### ISSUE TITLE
Iago issue since last version of RM stable update

### ISSUE THREAD

**Issue by nicopilami** [rmkit-dev/rmkit#165]
Hi since the last RM update, I reenabled the Toltec packages. Iago is starting, displays the menu, draws the circle (for instance) but pinching or whatever gesture I try does not modify the shape. any idea ? thanks

**Comment by raisjn** [comment]
are you using stylus or finger to modify the shape size? it should only support the stylus

**Comment by nicopilami** [comment]
uhhhh I'll try. I used to move with fingers. I'll let you know thanks

**Comment by nicopilami** [comment]
that did the trick !  thanks for the solution !

**Comment by nicopilami** [comment]
Hi
This was the point!
Thanks for the help
Regards
