### ISSUE TITLE
[simple] Images do not render

### ISSUE THREAD

**Issue by katlyn** [rmkit-dev/rmkit#168]
I've been messing with simple a bit, and was wondering why none of my images were rendering - I considered if I might have somehow had incompatible formats, so I ended up extracting the `bomb-solid.png` image that's used in the example and ended up getting the same result with no images being displayed. My script is using the same markup as the example on https://rmkit.dev/apps/sas, but I've included my script below as well as a photo of the output on the remarkable.

```bash
#!/bin/bash

cat << EOF | /opt/bin/simple
button 50 50 200 50 I'm a button
button 50 150 400 50 I'm a different button
label 50 100 300 50 I'm some text
image 50 200 200 200 /home/root/bomb-solid.png
[paragraph 80 450 800 200 I'm multi-line text, I'm multi-line text, I'm
multi-line text, I'm multi-line text, I'm multi-line text, I'm multi-line text,
I'm multi-line text, I'm multi-line text, I'm multi-line text, I'm multi-line
text, I'm multi-line text, I'm multi-line text, I'm multi-line text, I'm
multi-line text, I'm multi-line text, I'm multi-line text,]
EOF
```
![image](https://user-images.githubusercontent.com/17418611/157186139-0a08a6f6-aeab-4b8b-9b4d-f8d314ff0a37.png)

There is also no output on the command line that would suggest that anything went wrong.
![image](https://user-images.githubusercontent.com/17418611/157186222-efd21de2-a7e5-4a7e-90e0-1739d5f03657.png)

For debugging purposes, here is the png that I used for `bomb-solid.png`.
![bomb-solid](https://user-images.githubusercontent.com/17418611/157186366-7b31ac7d-e19f-4fb4-aec3-ed2b01189ea4.png)

**Comment by katlyn** [comment]
Disregard, after further investigation it appears that the latest version of simple was not installed by opkg. After updating images appear to be functioning as they should.

**Comment by raisjn** [comment]
thanks for trying out SAS! (and thanks for filing bugs - it lets me know its being used :D)
