### ISSUE TITLE
[remux] Swipe up gesture does not open remux (rM2, v2.12.3.606)

### ISSUE THREAD

**Issue by hellerbarde** [rmkit-dev/rmkit#173]
I installed it via Toltec:
```
opkg install remux
systemctl disable --now xochitl
systemctl enable --now remux
```

Unfortunately, swiping up doesn't make remux appear at all. How can I provide better information to debug this?

**Comment by SirDedale** [comment]
Looks like I experience the same thing. Updated RM2, then ddvl and finally toltec pkgs. 
remux doesn't show up anymore. Tried to systemctl stop xochitl and systemctl start remux as well.

**Comment by raisjn** [comment]
it is likely related to a new release, right? rm2fb may not support v2.12.3.606 (is it beta?)

**Comment by raisjn** [comment]
can you share the remux logs after performing the swipe? `journalctl -u remux`. it sounds like xochitl is displaying fine, so the issue wouldn't be in rm2fb.

**Comment by mariusdkm** [comment]
So I have almost the same issue, but remux seems to be working, but it takes at least 10 swipes to get it to show up.
I got remux and ddvk-hacks installed with my remarkable 2 with version 2.12.3.606.
The logs seem to be fine, no errors and the touch swipe gestures seem to be registered.
Maybe it has something to do with this commit https://github.com/rmkit-dev/rmkit/commit/83a60d6ff1788308655c4153f9ea7f748957a2fc ?

**Comment by raisjn** [comment]
what is your swipe gesture? i just upgraded to  2.12.3.606. and remux works fine. i'm on remux 0.2.2-1. i will install ddvk-hacks now and try it out

**Comment by raisjn** [comment]
i just tried out ddvk-hacks and the swipe gesture (one finger upwards on either side of the display) still works. maybe your fingers are larger than mine? (try swiping with just the tip of the index finger?)

**Comment by mariusdkm** [comment]
So without the palm filter it's working every try, I then reinstalled the recent version from toltec and its back to only working only every so often. 

> maybe your fingers are larger than mine? (try swiping with just the tip of the index finger?)

I wouldn't say that I have big fingers, I tried with my pinky but that doesn't seem to change anything.

> what is your swipe gesture?

I don't have anything changed from the default installation. I always swipe on the far right from the lower third to the upper third of the screen.

**Comment by raisjn** [comment]
fixed in https://github.com/rmkit-dev/rmkit/commit/2b37e6e807842373fd5293496e29e1f09205db91, it's available on the build server: https://build.rmkit.dev/master/latest/rm/remux

i made a PR request on toltec to make this off by default: https://github.com/toltec-dev/toltec/pull/588 

thanks for debugging this and figuring out the issue! (i would have not found it without your help)

**Comment by Groxx** [comment]
Yep, palm rejection fits what I'm seeing: if I swipe with my thumb flat, it ignores me.  If I swipe with just the tip, it works essentially every time.

Probably just over-enthusiastic palm detection.
