### ISSUE TITLE
[simple] textinput misses capital "N" and "M"

### ISSUE THREAD

**Issue by plan5** [rmkit-dev/rmkit#174]
When pressing shift on the onscreen keyboard, the letters n and m are not capitalized, so it is not possible to type N and M with simple.

Toltec package information:

Package: simple
Version: 0.1.5-2
Depends: rm2fb-client, display
Status: install user installed
Section: devel
Architecture: rmall
Maintainer: raisjn <of.raisjn@gmail.com>
Size: 128033
Filename: simple_0.1.5-2_rmall.ipk
Description: Simple app script for writing scripted applications
Installed-Time: 1649404585

**Comment by raisjn** [comment]
I'll take a look soon, might have time tomorrow night but am out of town until the weekend. feel free to pr, otherwise I'll get to it

**Comment by plan5** [comment]
Fixed with merge of #176 :+1:
