### ISSUE TITLE
[harmony] input for drawing on Kobo

### ISSUE THREAD

**Issue by plan5** [rmkit-dev/rmkit#175]
Harmony starts without issues on my Kobo Clara HD, thanks!

However, I cannot draw anything without a pen input device, which the Kobo doesn't support.

Am I missing something obvious?

If not, a solution might be to extend the "no touch feature" to painting with touch as an option, maybe?

**Comment by raisjn** [comment]
harmony now supports drawing on kobo with finger input :-D
