### ISSUE TITLE
[simple] Inaccurate information on spec

### ISSUE THREAD

**Issue by Jayy001** [rmkit-dev/rmkit#178]
It should be worth noting that on the spec, it doesn't specific that the keywords given are only supported for `x, y` and not `width, height`

```
widgets are specified as their x, y, width and height parameters, followed by zero or more values.

x and y must be an integer or a percentage value or a keyword

w and h must be an integer or a percentage value or a keyword

supported keywords are:

same - keep the same value as the previous item
step - previous item’s coord + the previous item’s size
```

If you try to use these keyword for `width` or `height` it'll spurt out an error about not being able to convert it into an integer 

However, `width` and `height` do accept one keyword which is `w` or `h` - however this is not documented anywhere on the spec so no clue on what it does

**Comment by raisjn** [comment]
thank you, docs are updated
