### ISSUE TITLE
[harmony] file format - timestamps?

### ISSUE THREAD

**Issue by zeigerpuppy** [rmkit-dev/rmkit#179]
I am interested in hacking up a sound recording app for reMarkable2.  The plan is to use a USB mic and record sound that can be referenced to pen strokes (so that the sound that was recorded at the time of the stroke can be replayed).  This is a really useful feature for recording lecture notes.  (For examples of similar see Livescribe pen and new Huawei MatePad Paper - both can sync sound recorded to pen stoke)

I looked in to the .rm lines format but unfortunately it doesn't store the timestamp of each stroke - and the file is only written to disk on exit so can't watch file and grab timestamps that way.

Does the file format for harmony have a format that could be used to store the stroke timestamps?

**Comment by raisjn** [comment]
no, harmony only uses raw bitmaps, sorry!
