### ISSUE TITLE
[docs] write app tutorial for rmkit

### ISSUE THREAD

**Issue by raisjn** [rmkit-dev/rmkit#18]

**Comment by ademasi** [comment]
Hi Raisjn, 

I am super interested to see a tutorial for rmkit and how to use it in a project.

Right now, I am trying to include rmkit.h as a library in a rust app for the remarkable that I am hacking around (mostly to learn rust and epaper based app development).  Do you know anything about using the [bindgen crate ](https://rust-lang.github.io/rust-bindgen/tutorial-3.html)?  My build.rs file looks like that :
``` rust
extern crate bindgen;

use std::env;
use std::path::PathBuf;

fn main() {

    // The bindgen::Builder is the main entry point
    // to bindgen, and lets you build up options for
    // the resulting bindings.
    let bindings = bindgen::Builder::default()
        // The input header we would like to generate
        // bindings for.
        .header("rmkit.hpp")
        // Tell cargo to invalidate the built crate whenever any of the
        // included header files changed.
        // Finish the builder and generate the bindings.
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
```
I had to change the name of the file, else clang was expecting a C header and not a C++ header. I used  make docker to generate  the .h file. 

The error I get when I run cargo build:
```rust
Caused by:
  process didn't exit successfully: `/home/alex/git/remarkable/ahau/target/debug/build/ahau-556c751751c7b3e2/build-script-build` (exit code: 101)
  --- stderr
  rmkit.hpp:44154:14: error: use of undeclared identifier 'std'
  rmkit.hpp:44281:10: fatal error: 'vector' file not found
  rmkit.hpp:44154:14: error: use of undeclared identifier 'std', err: true
  rmkit.hpp:44281:10: fatal error: 'vector' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:20:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If you could point me in any direction of how do it, I would be grateful.

Regards, Alex.

**Comment by raisjn** [comment]
hi alex!

  my first response is: what about libremarkable? it's a rust based lib for remarkable dev and a few apps are built / ported using it (plato, retris, chessmarkable, whiteboard from fenollp, etc)

 after that: this is a cool idea!  i don't have ideas about what is going wrong, as i haven't really used rust before. maybe @linuscde has some ideas? 

  that said, i will also prioritize writing some tutorial for rmkit to show how to build simple apps and draw to screen, etc.

**Comment by LinusCDE** [comment]
Hi,

I sadly haven't had the opportunity to use rmkit, yet (even though I wanted to for a long time).

Libremarkable is nice, but I think the UI-System from rmkit is easyier to use than libremarkable for doing uis. libremarkable has a `appctx.rs` which provides some ui stuff, but usually need more or find creating the objects to cumbersome.

For retris, I built a super simple "game engine" that manages scenes and wraps the framebuffer in a canvas struct (chessmarkable used the same). So libremarkable itself basically provides stuff like draw rect/text/image/... and various refresh modes as well as giving access to formatted input events.

So for a UI, rmkit is probably better suited and allows to make faster UI creation. I got my feet wet with bindgen [here](https://github.com/LinusCDE/rpi-epaper-mqtt-receiver) (i think the ffi or ffi2 branch), but the sample above seems even better than what I did (also my rust code was horrible at that point).

So creating a `rmkit-sys` lib would probably be very nice. I hope that I'll get time to help with that, but I fear that I might not find the time for it.

**Comment by ademasi** [comment]
Hi, 

Indeed, libremarkable would be the ideal candidate, but from what I saw in their documentations and the APIs, rmkit seems to be easier to understand and allows for shorter development time to go from idea to functional UI. 

Thank you both for your inputs. I will see what I can do :)

**Comment by LinusCDE** [comment]
@ademasi Agreed. The point of libremarkable is mainly to give you easy access to the hardware. Not really to give you an easy UI toolkit which rmkits intention seems to be. rmkit is the better choice for you in this case.

**Comment by raisjn** [comment]
rmkit uses subclassing for defining user components (for example, to add custom handlers for events), does rust ffi support writing child classes from rust?

if not, then rmkit will need to expose other ways of customizing widget behavior

**Comment by LinusCDE** [comment]
I'm not sure on the state of C++ integration with rust (there should be some however). It would probably require to create Rust versions of all the classes which would equal somewhat of a rewrite. At that point the challenge of building structures for UIs in rust will also appear as UI systems often don't mix well with rusts idea of ownership (though there are some dirty hacks around it).

**Comment by raisjn** [comment]
i've written up a couple tutorials in docs/ a few months ago and it seems a few people have been able to build apps (remarkable puzzles, rpncalc, reBook), so i'm happy with that and will close this out
