### ISSUE TITLE
[simple] Support for custom fonts

### ISSUE THREAD

**Issue by Jayy001** [rmkit-dev/rmkit#181]
Would be interesting to have some custom fonts availability!

**Comment by raisjn** [comment]
you can use custom fonts by setting an env variable, see the line: https://github.com/rmkit-dev/rmkit/blob/master/src/rmkit/fb/stb_text.cpy#L29

let me know if it works!

**Comment by tenJirka** [comment]
I can confirm that changing system variable RMKIT_DEFAULT_FONT to path to desired font works and changes the font.
