### ISSUE TITLE
[remux] Remarkable 1 stop syncing after remux service activation

### ISSUE THREAD

**Issue by odisseo79** [rmkit-dev/rmkit#188]
Dear all,
after remux installation and service activation, remarkable 1 stop syncing with the cloud.
The only way I found to recover synchronization is installing a firmware update.
I made the test a couple of times (I had to switch to the beta firmware program) and every time the issue comes back.
I installed remux both via binary and via toltec, the result is the same.

Anyone else with the same issue?

Regards
Odi

**Comment by Eeems** [comment]
It looks like you also opened an issue on toltec for this. Is the issue with toltec or remux?

**Comment by raisjn** [comment]
is this the same as https://github.com/rmkit-dev/rmkit/issues/183#issuecomment-1324698729 ?

**Comment by odisseo79** [comment]
@raisjn 
Yes, i was not able to find a similar issue searching on the web.
I try to apply the solution described there.

Thanks

**Comment by Eeems** [comment]
> @raisjn Yes, i was not able to find a similar issue searching on the web. I try to apply the solution described there.
> 
> Thanks

The solution there should be automatically applied with toltec at this point. If it's not working, further investigation would be required.
