### ISSUE TITLE
documentation for /home/root/.config/remux/remux.conf?

### ISSUE THREAD

**Issue by jdkruzr** [rmkit-dev/rmkit#190]
if there is documentation somewhere for all the options available in this file, I can't find it. right now mine looks like this:

```
Caelum: ~/.config/remux/ cat remux.conf 
launch_gesture=gesture=tap;fingers=5
back_gesture=gesture=tap;fingers=4
```

this results in too many false activation events while I'm writing, so I'd like to switch it to something like "swipe down on the left side of the screen." I know this is possible from other comments here but no one ever mentions how they set it up. help?

**Comment by Eeems** [comment]
Have you read this yet? https://github.com/rmkit-dev/rmkit/tree/master/src/remux#config-017

**Comment by raisjn** [comment]
what eeems said. also look at genie readme for how to setup the swipe zone.

**Comment by jdkruzr** [comment]
do I understand correctly that the configuration in this file specifically, even though there is a "gesture=" setting, does not support any gestures other than tap, and that any others require you to disable gesture support in this file and use genie instead?

I'm going to try the palm rejection feature. I really appreciate all the work you've put in here but just having a reverse-time-order changelog for documentation is Not Great.

**Comment by raisjn** [comment]
https://github.com/rmkit-dev/rmkit/blob/master/src/remux/launcher.cpy#L72

any genie config should work, so you can setup swipe. these are up swipes, should be easy to adapt.

re: docs: great idea, contributions are welcome

**Comment by jdkruzr** [comment]
thanks - am I crazy or should this in fact work?

> This sample configuration would enable palm detection as above and configure "single-finger swipe up on the lower left" as "back" with "single-finger swipe up on the lower right" as "launch remux":
> 
> ```
> filter_palm_events
> back_gesture=gesture=swipe;direction=up;fingers=1;zone=0 .5 0.1 1
> launch_gesture=gesture=swipe;direction=up;fingers=1;zone=0.9 .5 1 1
> ```
> 
>

**Comment by raisjn** [comment]
i don't remember if 0,0 is upper left or bottom right, but I think upper left. try slower gesture? do the original swipe gestures work for you?

**Comment by jdkruzr** [comment]
yes, if I switch to tap instead (I picked 5 fingers and 4 fingers) it works fine. according to the documentation 0,0 is upper left.

**Comment by raisjn** [comment]
have your watched the video of swipes in remux? you might need to change the minimum swipe amount
