### ISSUE TITLE
[genie] Add support for genie.conf.d config folder

### ISSUE THREAD

**Issue by Eeems** [rmkit-dev/rmkit#192]
Add support for loading config files found in `/opt/etc/genie.conf.d/`, this way packages in toltec could include genie configuration that will automatically work, instead of requiring users to modify their genie.conf, or adding some complex parsing to attempt to add it to the file.

**Comment by Eeems** [comment]
Just poking this again. I think this would be useful at allowing genie to work out-of-box for users instead of having them have to get an example config from someone and then figure out how to configure it themselves.

**Comment by raisjn** [comment]
good idea, will try to implement soon

**Comment by raisjn** [comment]
something like this: https://github.com/rmkit-dev/rmkit/commit/130c13f8ce10b1d9ba2b974ff0f5f36851595e3a

just need to test it on device and make sure no problems

**Comment by raisjn** [comment]
this needs testing, but i'll close it out for now
