### ISSUE TITLE
[harmony] Bus error when trying to load with a different framebuffer resolution

### ISSUE THREAD

**Issue by Eeems** [rmkit-dev/rmkit#194]
If you try to load harmony where the current raw image was created against a different framebuffer resolution, it will either corrupt what is displayed, or create a bus error.

Ideally, it should detect a change in framebuffer resolution and attempt to resize the data to fit.
![2023-07-24T152911 091](https://github.com/rmkit-dev/rmkit/assets/1176979/3908028e-865d-46b1-8f26-ba73f9094c03)
![2023-07-24T152837 581](https://github.com/rmkit-dev/rmkit/assets/1176979/641a5b9f-4436-42bc-85ed-c04be5f715a8)

**Comment by raisjn** [comment]
thanks for filing! a thought i had here was to use the first few bytes of the raw file to store the resolution of the framebuffer and then to change behavior if the resolutions are incompatible with the current framebuffer. (resize it? discard it?)

**Comment by Eeems** [comment]
Attempting to resize would be nice, assuming it's not too difficult to do.
