### ISSUE TITLE
Error when trying to create a build

### ISSUE THREAD

**Issue by YogatBear** [rmkit-dev/rmkit#199]
I was trying to compile an implementation of Iago. I tried runnig make and got this:
```
make compile_remarkable
make[1]: Entering directory '/mnt/c/Users/Yoav/Documents/GitHub/rmkit/src/iago'
mkdir ../build 2> /dev/null || true
arm-linux-gnueabihf-g++ -c ../vendor/stb/stb.cpp -o ../build/stb.arm.o -fPIC -Os
CXX=arm-linux-gnueabihf-g++ okp -ig "RMKIT_IMPLEMENTATION" -ns -ni -for -d ../.iago_cpp/ -o ../build/iago main.cpy ../build/stb.arm.o -- -D"REMARKABLE=1" -D"RMKIT_IMPLEMENTATION" -pthread -lpthread -fdata-sections -ffunction-sections -Wl,--gc-sections -O2
/bin/sh: 1: okp: not found
make[1]: *** [../actions.make:36: compile_remarkable] Error 127
make[1]: Leaving directory '/mnt/c/Users/Yoav/Documents/GitHub/rmkit/src/iago'
make: *** [../actions.make:13: compile] Error 2
```

**Comment by YogatBear** [comment]
Updated with relevant error

**Comment by Eeems** [comment]
You don't have okp installed. https://github.com/rmkit-dev/rmkit/blob/master/docs/BUILDING.md#linux

**Comment by YogatBear** [comment]
> You don't have okp installed. https://github.com/rmkit-dev/rmkit/blob/master/docs/BUILDING.md#linux

My bad, I missed it. I now get a compiled file but while building I get some errors:
```
missing file: ../shared/string.h
MISSING FILE! /mnt/c/Users/Yoav/Documents/GitHub/rmkit/src/.rmkit.h_cpp/shared/string.h
missing file: stb_image.h
missing file: stb_image_resize.h
```
Thanks for the help!

**Comment by YogatBear** [comment]
Trying to run <code>make docker</code> brings up this error:
```
 docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/01285378a1e557ae9492fac1d36e7b4794c569d9cb8e829cc9d1d688d708f455': mkdir /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/01285378a1e557ae9492fac1d36e7b4794c569d9cb8e829cc9d1d688d708f455: file exists.
make: *** [Makefile:71: docker] Error 125
```
The artifacts folder that gets created is called <code>artifacts</code> and is empty.

**Comment by Eeems** [comment]
> > You don't have okp installed. https://github.com/rmkit-dev/rmkit/blob/master/docs/BUILDING.md#linux
> 
> My bad, I missed it. I now get a compiled file but while building I get some errors:
> 
> ```
> missing file: ../shared/string.h
> MISSING FILE! /mnt/c/Users/Yoav/Documents/GitHub/rmkit/src/.rmkit.h_cpp/shared/string.h
> missing file: stb_image.h
> missing file: stb_image_resize.h
> ```

Does the file it's complaining about exist? My guess is that it failed to get generated, and there is an error further up the stack you need to look at.

> 
> Also this error when running `resim ./src/build/iago`:
> 
> ```
> Traceback (most recent call last):
>   File "/home/yogatbear/.local/bin/resim", line 8, in <module>
>     sys.exit(main())
>   File "/home/yogatbear/.local/lib/python3.10/site-packages/remarkable_sim/sim.py", line 337, in main
>     gui = GUI(root, args.display_scale, args.executable)
>   File "/home/yogatbear/.local/lib/python3.10/site-packages/remarkable_sim/sim.py", line 199, in __init__
>     self.fifo_stylus = makefifo(path_fifo_stylus)
>   File "/home/yogatbear/.local/lib/python3.10/site-packages/remarkable_sim/evsim.py", line 35, in makefifo
>     os.mkfifo(path)
> OSError: [Errno 95] Operation not supported
> ```
> 
> Thanks for the help!

Just to confirm, you're running this in linux and not something else, right? It appears that your OS doesn't support creating a fifo.

> Trying to run `make docker` brings up this error:
> 
> ```
>  docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/01285378a1e557ae9492fac1d36e7b4794c569d9cb8e829cc9d1d688d708f455': mkdir /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/01285378a1e557ae9492fac1d36e7b4794c569d9cb8e829cc9d1d688d708f455: file exists.
> make: *** [Makefile:71: docker] Error 125
> ```
> 
> The artifacts folder that gets created is called `artifacts` and is empty.

You might need to run `make clean` before trying to `make docker`. I'm not sure.

**Comment by YogatBear** [comment]
> You might need to run `make clean` before trying to `make docker`. I'm not sure.

Restarting Docker fixed it, but now I get this:
```
bash scripts/build/docker_release.sh
: file exists.response from daemon: mkdir /mnt/c/users/yoav/documents/github/rmkit/artifacts
See 'docker run --help'.
make: *** [Makefile:71: docker] Error 125
```
I made sure <code>rmkit/artifacts<\code> doesnt exist before compiling. the empty <code>artifacts<\code> is still created.

**Comment by Eeems** [comment]
> > You might need to run `make clean` before trying to `make docker`. I'm not sure.
> 
> Restarting Docker fixed it, but now I get this:
> 
> ```
> bash scripts/build/docker_release.sh
> : file exists.response from daemon: mkdir /mnt/c/users/yoav/documents/github/rmkit/artifacts
> See 'docker run --help'.
> make: *** [Makefile:71: docker] Error 125
> ```
> 
> I made sure `rmkit/artifacts` doesnt exist before compiling. the empty `artifacts` is still created.

It's created by the script that runs docker.
https://github.com/rmkit-dev/rmkit/blob/ef4d98be47543a5f12acd37b864c948569a4ad2b/scripts/build/docker_release.sh#L1-L4

The error you had before was specifying `/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/01285378a1e557ae9492fac1d36e7b4794c569d9cb8e829cc9d1d688d708f455` though, which is the bind mount path it's creating to mount the folder to.

This also answers my question about if you are running this on linux or something else. You appear to be running this in WSL on a windows machine. Is this WSL1 or WSL2? Are you running docker inside WSL, or from the host machine?

**Comment by YogatBear** [comment]
> This also answers my question about if you are running this on linux or something else. You appear to be running this in WSL on a windows machine. Is this WSL1 or WSL2? Are you running docker inside WSL, or from the host machine?

Running the docker on WSL2 Ubuntu. Running through windows gives the same result.

**Comment by Eeems** [comment]
I'm able to run `make docker` on linux with no issues. Could this be because the folder you have the source checked out to is on the windows host system and NTFS isn't playing nice?

**Comment by YogatBear** [comment]
> I'm able to run `make docker` on linux with no issues. Could this be because the folder you have the source checked out to is on the windows host system and NTFS isn't playing nice?

Thnaks for your patience, that seems to have been the issue...
I can now get a build which I can run, but I've been having a few issues with it to work. Maybe you could helo me there?

I tried running:
<code> LD_PRELOAD=usr/lib/librm2fb_server.so.1.0.1 iago</code>
and got this:
<code>[ LD_PRELOAD=usr/lib/librm2fb_server.so.1.0.1 iagonew](ld.so: object 'usr/lib/librm2fb_server.so.1.0.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored)</code>

and after my iago build is running:
```
W: 260 H: 1408 S: 260
XRES 260 YRES 1408 BPP 16 GRAYSCALE 0
ERROR OPENING INPUT DEVICE /dev/input/event3
ERROR OPENING INPUT DEVICE /dev/input/event4
```

**Comment by YogatBear** [comment]
> > I'm able to run `make docker` on linux with no issues. Could this be because the folder you have the source checked out to is on the windows host system and NTFS isn't playing nice?
> 
> Thnaks for your patience, that seems to have been the issue... I can now get a build which I can run, but I've been having a few issues with getting it to work. Maybe you could help me there?
> 
> after my iago build is running:
> 
> ```
> W: 260 H: 1408 S: 260
> XRES 260 YRES 1408 BPP 16 GRAYSCALE 0
> ERROR OPENING INPUT DEVICE /dev/input/event3
> ERROR OPENING INPUT DEVICE /dev/input/event4
> ```

Managed to bypass this by duplicating input1 and Input2 to 3 and 4.
Not sure if this breaks anything, but I can now build and run. Thanks for your help!
