### ISSUE TITLE
[simple] Problem with diacritics

### ISSUE THREAD

**Issue by tenJirka** [rmkit-dev/rmkit#202]
Hi, I'm trying to build a simple app with this nice and easy to use tool, but I find out, that if you try to create label for example with word "Dovolená", it will skip the letter "á" at the end (these special letters are pretty common in my language - Czech) and write only "Dovolen".

Tried with:
`echo "label 150 150 150 400 Dovolená" | /opt/bin/simple`

I guess it have probably something to do with encoding and it do not happen when the letter is not at the end of the text.

I would also like to ask, why are multiple spaces joining to one - for example `"Wo       rd"`  will end up as `"Wo rd"`, I tried to use this to do some padding, but unsuccessfully.

**Comment by tenJirka** [comment]
I just find another bug, if you try to add any of these letters in upper case to label/button/etc., simple will crash. If it will be at the end of text, it will not, because it will not try render at all. 
For example letters `Č, Ř, Á` will cause the crash.

**Comment by raisjn** [comment]
thank you, will investigate - am out of town until next week, though.

can you share some words that cause the crash?

**Comment by raisjn** [comment]
I found the issue with the end of line character - the rtrim function is bad. I'm sort of able to repro the crash with uppercase + diacritic, but it only happens if I do something like this: 

"ČŘÁ" - this crashes
"ČŘÁs" - this doesn't crash

**Comment by tenJirka** [comment]
Okay, the behavior is actually weirder than I thought.
Word "ČŘÁ"  do not crash for me, but it do not render. 
Words "Dovolená Řecko" used as written crash.
Words "Dovolená řecko" is okay.
Word "Dovolená" and  "Řecko" not used together doesn't crash.

**Comment by raisjn** [comment]
it has to do with the character widths - i'm not sure exactly what is going on yet but I tried out a few situations and was able to cause crashes. still debugging it, :-(

**Comment by tenJirka** [comment]
You are right, I can confirm that when I change font by system variable RMKIT_DEFAULT_FONT to /usr/share/fonts/ttf/noto/NotoSans-Bold.ttf, it wont crash.
So that's a workaround.

**Comment by raisjn** [comment]
the trim should be fixed, but the overall issue is still there

**Comment by raisjn** [comment]
I will look into it more this week, sorry for the delay

**Comment by raisjn** [comment]
this should be more addressed by 1a7887f1b353d5186d8e1eac196464280d7a07dc. there is probably a better long term solution, though. will close this out when it lands in toltec
