### ISSUE TITLE
Add support for Kobo Sage

### ISSUE THREAD

**Issue by sohansubhash** [rmkit-dev/rmkit#207]
Is there a blocker preventing support for the Kobo Sage from being added?

**Comment by raisjn** [comment]
I need to check on the details for what is required for Kobo Sage support. sometimes, the devices share the same display + chipset (and then it is easy), other times they have relatively unique display drivers or quirks. 

 I will work on a way for faster bring up of new devices, though.

**Comment by raisjn** [comment]
this should work now with fbink as the back end. please  look in the build server
