### ISSUE TITLE
[harmony] Kobo Elipsa 2E eraser support

### ISSUE THREAD

**Issue by sre3** [rmkit-dev/rmkit#211]
When using the eraser on the stock MPP2.0 pen provided with the kobo elipsa 2e, it acts as a regular stylus tip input without tilt support. It would be great if using the eraser automatically selected the eraser tool :)

**Comment by raisjn** [comment]
I'll charge the elipsa and check on it, thanks for using harmony!

**Comment by raisjn** [comment]
please try the latest build of harmony on https://build.rmkit.dev/master/latest/kobo/, support was added in 75d76962d4b7346c1197663e636445ed05301c35
