### ISSUE TITLE
Remux crashes after restarting rM1

### ISSUE THREAD

**Issue by Lebesge** [rmkit-dev/rmkit#216]
- rM1 version: 2.6.1.71

## Step to produce:
1. Install remux by 
``
opkg install remux & systemctl enable --now remux
``
After that my rM restart and I can open the remux bar by holding the middle button. 
![9499fc50846d640ed43a40b6794db649_720](https://github.com/rmkit-dev/rmkit/assets/131115024/1cc47132-b5a1-407a-94d2-3c48f28b9541)

2. Restart rM. Now remux crash like this when I hold the middle button:
![0c9f75df8cc07513672e127c5d86e784](https://github.com/rmkit-dev/rmkit/assets/131115024/1a43ba9f-19ee-44f3-9d92-39f2134269d2)

3. I try to unistall and install remux for several times but still have the issue. 
 Hope someone could help me, thanks!

**Comment by Lebesge** [comment]
I have just fixed it. It seems that the auto-startup of koreader and remux conflict. Sorry to put this issue.

**Comment by raisjn** [comment]
no problem, thanks for using remux and enjoy the tablet :-)
