### ISSUE TITLE
[remux] remux may prevent the device from entering sleep triggered by xochitl

### ISSUE THREAD

**Issue by plredmond** [rmkit-dev/rmkit#226]
### description

remux can prevent the device from entering sleep

* steps to reproduce
  * in xochitl, press the suspend hardware-button
  * screen shows sleep image
  * count to 4
  * perform the remux summoning gesture

* expected behavior
  * the device should go to sleep
* actual behavior
  * remux appears on screen
  * device remains awake

### additional notes

* if you wait 12 seconds before performing the gesture the device goes to sleep
* this is possibly not a bug at all; feel free to close!
  * there seems to be a delay between when the screen blanks to the sleeping image and when the device actually enters sleep (per journalctl)
  * there's a strong argument that remux shouldn't detect the buttonpress and disable its input during this delay, because that would just be more complexity

### versions

* 3.3.2.1666_reMarkable2-ihUirIf133-.signed
* remux - 0.3.0-4

**Comment by plredmond** [comment]
my real reason for writing this issue is to request some documentation on remux's webpage about when and how it should be expected to go to sleep; i've had problems in the past where it appears to be asleep, but isn't, and the battery has drained.. i'd like to avoid that, but i don't know how... as the developer of remux, how do you ensure your device sleeps when you want it to sleep?

**Comment by Eeems** [comment]
When xochitl is active, remux doesn't handle suspend. Which means xochitl is handling the power button press. Xochitl also doesn't use systemd for suspend, and just uses `/sys/power/state` directly. As there is no way to grab the power button input, you can't intercept this to know that xochitl is starting to suspend and do anything.

I've written a preload library that captures xochitl's `/sys/power/state` call and uses systemd instead, so that hooks can run on suspend/resume. https://github.com/Eeems-Org/sysfs_preload It's not quite ready though as it appears to not play nice with rm2fb's preload.

**Comment by plredmond** [comment]
That's helpful context. Thank you. I'm going to try to disable remux's power management and rely on xochitl's for now.

**Comment by Eeems** [comment]
> ...  I'm going to try to disable remux's power management and rely on xochitl's for now.

I don't think you understand what I'm saying, xochitl's power management is what is causing the issue. Disabling remux's power management just means the device will no longer auto suspend when xochitl is no longer the active application, and the issue you have encountered will still be present when xochitl is active.

**Comment by plredmond** [comment]
I understood what you said, and the consequence (that I must switch to xochitl otherwise the device won't sleep). It's just that I don't want to think about the two separate state machines. So I'd like to disable one of them. I don't know how to disable xochitl's power management, but remux has documentation on how to disable its power management.

**Comment by Eeems** [comment]
> I understood what you said, and the consequence (that I must switch to xochitl otherwise the device won't sleep). It's just that I don't want to think about the two separate state machines. So I'd like to disable one of them. I don't know how to disable xochitl's power management, but remux has documentation on how to disable its power management.

Disabling xochitl's power management only allows you to disable the auto suspend/power down in the menus. You can't disable its power button handling.

**Comment by plredmond** [comment]
Ok, thanks for explaining. It seems like there are (at least) four separate ways the machine might sleep:

* xochitl (when active) may detect the hardware-button and sleep
* remux may detect the software-button "suspend" and sleep
* xochitl (when active, or after being reactivated by remux) may hit its idle timeout and sleep
  [can be disabled in xochitl "battery" menu]
* remux may hit its idle timeout and sleep
  [can be disabled [with config file](https://github.com/rmkit-dev/rmkit/tree/master/src/remux#disable-power-management-018)]

**Comment by Eeems** [comment]
That would be correct

**Comment by plredmond** [comment]
Ok, from reading those four methods of entering sleep, there's only one problem (number 3, after being reactivated by remux, when xochitl forces sleep wrongly) and that's what your sysfs_preload work may address. Correct?

**Comment by Eeems** [comment]
It won't really address it, it'll just mean that you can run code before suspend and after resume.

**Comment by plredmond** [comment]
Ah, well.

---

One last question (thanks so much for explaining all this so far!)

I tried [number 2](https://github.com/rmkit-dev/rmkit/issues/226#issuecomment-2183479601), activating remux and pressing the "suspend" software-button when xochitl was active, and upon resume there were several odd behaviors:

1. Only part of xochitl was drawn to the screen, the rest retained the sleep image.
2. In ssh I issued `systemctl restart remux` but nothing happened.
3. I tried to reboot the machine, and it locked up while showing the "restarting" image.

Eventually I got impatient and tried holding the hardware-button for 30s for a reset, and was able to get the machine back.

**Comment by Eeems** [comment]
Restarting remux wouldn't cause xochitl to redraw to the screen. You only need to hold the power button for around 10 seconds to force power off the device.

Are you able to replicate the screen not fully updating consistently?

> the machine is resumed, but it's unable to restart remux in ssh

Could you explain what you mean by this?

**Comment by plredmond** [comment]
I'll try to make a repro and if I'm able, I'll post a separate issue.

>     the machine is resumed, but it's unable to restart remux in ssh

I mean, I used the hardware-button to resume the device. The screen did not update. Gestures didn't cause anything to happen. I was able to ssh into the device, so it was resumed. From that point, I tried `systemctl restart remux` (and consequently xochitl) but that hung. After 30s systemd killed remux and restarted it. Then the screen reactivated.

I'll try to see if there's anything in journalctl that might explain what's happening when the screen (and restarting remux) is hung.

**Comment by Eeems** [comment]
Restarting remux will not cause the screen to update, it'll just result in your opened app being closed. I would recommend just opening the remux menu, killing the app from there, and then reopening it.

My guess with the screen is that remux isn't waiting for it finish drawing before suspsending. That mixed with rm2fb on the rm2 would causing timing issues.

https://github.com/rmkit-dev/rmkit/blob/319779917fe147ff82a71f2ee5caeb0505454824/src/remux/launcher.cpy#L704-L762

**Comment by plredmond** [comment]
> Restarting remux will not cause the screen to update, it'll just result in your opened app being closed. I would recommend just opening the remux menu, killing the app from there, and then reopening it.

I think you misunderstood. In [this message](https://github.com/rmkit-dev/rmkit/issues/226#issuecomment-2183493795) and [this one](https://github.com/rmkit-dev/rmkit/issues/226#issuecomment-2183505190) I'm talking about after the device successfully suspends **and then resumes** (where suspend was initiated using the remux "suspend" software-button). *After resume* the screen doesn't (fully) activate. Sometimes the sleep image remains completely, sometimes xochitl will show the left part of its bottom-bar (power/wifi status). In all cases, the device is behaving strangely. The only way I've been able to get the screen to reactivate is to do `systemctl restart remux` and wait for a timeout after which systemd kills things. And even after that, the device is still behaving strangely (hangs on reboot).

**Comment by Eeems** [comment]
No, I do understand that it's on resume, and I still think that it's related to timing issues on resume as rm2fb still is working through it's draw queue. Remux tries to clear and then redraw the application screen while other updates are still underway, and leaves the screen in an incorrect state. Restarting remux would result in restarting applications and getting them to redraw themselves completely.

If enabling wifi completely resolves this, I don't know if @raisjn would want a different issue opened or not. What is being logged?

**Comment by plredmond** [comment]
> I would recommend just opening the remux menu, killing the app from there, and then reopening it.

In the state where the screen shows part of an application, gestures do not summon remux.

Here is an example of how the screen looks (it's the sleep image except for the this corner):

![out](https://github.com/rmkit-dev/rmkit/assets/51248199/1e692467-b322-46db-82cb-6ee9c380936e)

>  What is being logged?


At this point (after resuming and observing the partial-screen state) `journalctl` includes:

```
Jun 21 22:21:01 reMarkable remux[336]: brcmfmac              245760  0
Jun 21 22:21:01 reMarkable remux[336]: cfg80211              598016  1 brcmfmac
Jun 21 22:21:01 reMarkable remux[336]: brcmutil               16384  1 brcmfmac
Jun 21 22:21:01 reMarkable remux[188]: RELOADING WIFI DRIVERS
```

Since I cannot use the gesture to summon remux and kill the application, the device seems frozen. However, in `ssh` I can attempt to restart remux and whatever the current application is with `systemctl restart remux`. This hangs, during which the screen remains unchanged.

After about 1 minute 30 seconds, the restart completes. Now `journalctl` includes:

```
Jun 21 22:38:10 reMarkable remux[189]: CLEANING UP FB
Jun 21 22:38:10 reMarkable remux[239]: shutdown called
Jun 21 22:38:10 reMarkable systemd[1]: Stopping App launcher that supports multi-tasking applications...
Jun 21 22:38:10 reMarkable systemd[1]: remux.service: Main process exited, code=exited, status=15/n/a
Jun 21 22:39:40 reMarkable systemd[1]: remux.service: State 'stop-final-sigterm' timed out. Killing.
Jun 21 22:39:40 reMarkable systemd[1]: remux.service: Killing process 343 (modprobe) with signal SIGKILL.
Jun 21 22:39:40 reMarkable systemd[1]: remux.service: Failed with result 'exit-code'.
Jun 21 22:39:40 reMarkable systemd[1]: Stopped App launcher that supports multi-tasking applications.
Jun 21 22:39:40 reMarkable systemd[1]: remux.service: Found left-over process 343 (modprobe) in control group while starting unit. Ignoring.
Jun 21 22:39:40 reMarkable systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jun 21 22:39:40 reMarkable systemd[1]: Started App launcher that supports multi-tasking applications.

... <followed by normal remux start-up logs> ...
```
This stuff about modprobe seems wrong, given that the wifi device is disabled throughout this exercise by "flight mode".

Everything looks good, now. The device behaves normally.

Now if I `reboot` the device, it hangs. I've waited up to 3 minutes 30 seconds in this state, and the device doesn't complete the reboot.

To turn the device back on, hold the power button for 12 seconds, release for 1 second, hold the power button for 1 second. Now the device boots up, fresh. `journalctl -b -1` shows the gap:

```
Jun 21 22:44:09 reMarkable systemd[1]: Started Show reboot image.
Jun 21 22:44:22 reMarkable systemd[1]: [[0;1;39m[[0;1;31m[[0;1;39mRequested transaction contradicts existing jobs: Transaction for systemd-networkd.service/start is destructive (sh
utdown.target has 'start' job queued, but 'stop' is included in transaction).[[0m
Jun 21 22:44:22 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185msystemd-networkd.socket: Failed to queue service startup job (Maybe the service file is missing or not
 a non-template unit?): Transaction for systemd-networkd.service/start is destructive (shutdown.target has 'start' job queued, but 'stop' is included in transaction).[[0m
Jun 21 22:44:22 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185msystemd-networkd.socket: Failed with result 'resources'.[[0m
Jun 21 22:45:36 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mremux.service: State 'stop-final-sigterm' timed out. Killing.[[0m
Jun 21 22:45:36 reMarkable systemd[1]: [[0;1;39m[[0;1;31m[[0;1;39mremux.service: Killing process 343 (modprobe) with signal SIGKILL.[[0m
Jun 21 22:45:36 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mremux.service: Failed with result 'exit-code'.[[0m
Jun 21 22:45:36 reMarkable systemd[1]: Stopped App launcher that supports multi-tasking applications.
```

There's another failed modprobe. I suspect [rm2-suspend-fix](https://github.com/toltec-dev/toltec/blob/stable/package/rm2-suspend-fix/rm2-suspend-fix.sh) might be the issue, here.

**Comment by Eeems** [comment]
rm2-suspend-fix does unload/load the wifi modules when systemd is used, which remux might not be playing nice with anymore. You can try commenting out the script to see if it resolves it.

**Comment by raisjn** [comment]
for a while there was a wifi driver related bug and remux would reload the drivers,  see https://github.com/rmkit-dev/rmkit/blob/319779917fe147ff82a71f2ee5caeb0505454824/src/remux/launcher.cpy#L734

you can remove those lines and see if it fixes it. if so, we can figure out what to from there. 

thanks for reporting the issue, and thanks eeems for providing your usual stellar support!

**Comment by plredmond** [comment]
Commenting the content of `/lib/systemd/system-sleep/rm2-suspend-fix.sh` does seem to fix the issue while "flight mode" is active. (I've run through my repro twice; Repro is: (1) boot device, (2) sleep using remux "suspend" software-button, (3) resume.)

Looking at where https://github.com/rmkit-dev/rmkit/blob/319779917fe147ff82a71f2ee5caeb0505454824/src/remux/launcher.cpy#L734 takes place, it seems that it too might be a cause of a similar issue, if the modprobe was at fault. However, I just did my repro twice with no issue now.

**Comment by Eeems** [comment]
it's likely that this is a timing issue with modprobe not being happy with being run twice at the same time. I wouldn't recommend uninstalling rm2-suspend-fix, as it's required by default. Instead leave it commented. We'll have to sort out a better solution in toltec.

**Comment by plredmond** [comment]
Ok! Thanks for all your help, and thanks for your work on toltec. Feel free to close this, or I can.
