### ISSUE TITLE
[remux] better power management

### ISSUE THREAD

**Issue by raisjnn** [rmkit-dev/rmkit#24]
we received bug report from favored user:

> It seems to me that remux makes it difficult for the reMarkable to shut down automatically (using the settings in remarkable.conf) and for a reason that I don't understand when remux is enabled (I'm also tried with the latest build from toltec/testing) I need to try several time before the device accepts to boot. Maybe it's related to the way it's shut down, I've not been able to investigate this, but the problem goes away when I disable remux in systemctl.

this task is to bring power management up to snuff

**Comment by raisjnn** [comment]
we can do this with `rtcwake` and have working prototype, the next part is reading the timeout values from xochitl's config (instead of using our own?)

**Comment by ademasi** [comment]
I get the same issue. 
Also, when I try to shutdown the tablet with the button (long press). I get the image "reMarkable is powered off" but after sometime the image changes to the table is sleeping message. 

When I have the  "reMarkable is powered off" image I can still ssh to it, hence it's not off. If I use shutdown now, it will turn it off.

**Comment by raisjnn** [comment]
I've pushed a commit that atttempts to address problem 1 - **going into auto shutoff after 10 hours**. you can find the binary for it on the build server for testing: https://build.rmkit.dev/master/latest/files/ (if you can test it and report back in a day or two, that would be really useful). it's still not hooked up to xochitl.conf file yet. 

Thank you for highlighting problem 2! I can reproduce it, but I'm not sure what is causing it just yet. I can see that if `xochitl` is running as a service, then it works as expected, but if `xochitl` is running directly from remux, then the shutoff never finishes. I'm trying to come up with guesses / explanations for why this is. 

In general, the reason remux has these problems is because it has to take over power responbility from xochitl  (because xochitl could be suspended and the tablet would never go to sleep / turn off)

**Comment by raisjnn** [comment]
ah, i accidentally commented on the wrong issue (22). 

I had to pull in the big guns and ask bokluk for some advice, he mentioned that this (the not shutting down) is because xochitl needs to be started with --system argument. 

when xochitl --system is run, when xochitl exits, the system powers off. when it is just xochitl, then it is run in test mode and xochitl won't power off the system when it quits through the power menu.

i'll try it out later today, but if you want to verify, you (whoever is reading this task) can change the xochitl invocation to xochitl --system in launcher.cpy and use the power menu to turn on and off

**Comment by raisjnn** [comment]
676347d82368b822a6f53814b8b6b459af57a134 for `--system`

5a2a9aca90ed030b9296e46c7297580a8192d119 for autoshutoff after X hours

**Comment by raisjnn** [comment]
https://github.com/rmkit-dev/rmkit/commit/c7301ba3ffca17c728cd9f6a91faa17707a42457 for reading settings from xochit.conf, now it's ready to be merged into toltec testing

**Comment by myf** [comment]
another data point here having issue with the power button. I can't confirm if it's caused by remux, i should experiment turning remux off to see if there's a different result. but here's the problem: leaving it to sleep and it will turn itself off in a few hours. and when i try ro power it on by pressing the power button i find myself unable to. i would have to keep clicking it for a minute or two then at one point it registers and powers on. 

- build md5sum `fb602873fd3ff9c81b4b071bcaf43c7e39a437eff234cebd7087bf96f925bca9``
    - master/20200920_2318_d3ebde1/

**Comment by raisjnn** [comment]
merged latest into toltec (it should be the same file as you are already using, though)

thanks for investigating, myf! i just tested holding down power -> turn off -> holding power to turn on and it works as expected for me. so i wonder what the difference in our setups is.

**Comment by raisjnn** [comment]
synced offline with myf, i think that the power issue with the power button is mostly resolved on his hardware

**Comment by raisjnn** [comment]
received confirmation that both issues are resolved from other people, please re-open or add new issue if it happens again (or for more power management fixes)
