### ISSUE TITLE
[simple] Add flag to not clear the screen

### ISSUE THREAD

**Issue by Eeems** [rmkit-dev/rmkit#25]
I think it would be good to allow simple to run without clearning the entire screen. This would make it so that it could be used for simple scripts that want to display some extra information on the screen temporarily without wiping the screen content. Maybe a flag for framebuffer save/recall?

**Comment by raisjnn** [comment]
implemented @noclear with 8b8d020d24880e47341512c195c96e62bb31fd36 that tells simple to not clear the screen

not sure about 'framebuffer save/recall'
