### ISSUE TITLE
[remux] Lamy Button

### ISSUE THREAD

**Issue by AaronDavidSchneider** [rmkit-dev/rmkit#27]
Maybe I did something wrong, but is it possible that the lamy button hack of @ddvk conflicts the remux button listen service?

**Comment by ddvk** [comment]
xochitl has to be tun with the right parameter (-plugin evdevlamy)

**Comment by AaronDavidSchneider** [comment]
Thanks @ddvk. Just saw that this issue is actually a duplicate of #22.

**Comment by raisjnn** [comment]
thanks for opening! we will help finish that task this week
