### ISSUE TITLE
[remux] paging through apps doesn't work as expected

### ISSUE THREAD

**Issue by raisjn** [rmkit-dev/rmkit#29]
when paging through apps (when there are more than 8 or so apps), remux seems to dismiss itself. this is unexpected

**Comment by raisjnn** [comment]
fixed in https://github.com/rmkit-dev/rmkit/commit/8e56c61385fa5da73fbe4aefa1d7991ab82dfb89

**Comment by roosemberth** [comment]
@raisjn Did you forget to close the issue?

**Comment by raisjn** [comment]
thank you for reminding me! 

i left it open for a while so that people would see the issue if they came to check, but now the fix has been out for a while and is in toltec, so i will close it
