### ISSUE TITLE
[harmony] Save silently fails if the `/home/root/harmony` folder does not exist

### ISSUE THREAD

**Issue by matteodelabre** [rmkit-dev/rmkit#30]
Repro:

1. Remove the `/home/root/harmony` folder from the device.
2. Start harmony.
3. Save a drawing.
4. Nothing is saved, and the load dialog is empty.

**Comment by raisjnn** [comment]
Should be fixed in ff6c493f8a95f7c9f4da93da2c569120ab7c3845, but needs testing
