### ISSUE TITLE
Doesn't work on rM2

### ISSUE THREAD

**Issue by slowpoison** [rmkit-dev/rmkit#34]
I just got my rM2 and tried installing. Installation went fine, but I cannot seem to bring up the launcher.
For one, there's no home button.

**Comment by raisjnn** [comment]
Thank you for opening the issue and for your patience while we figure out rM2 stuff! The code in this repo is not expected to work on rM2 until we figure out how to write to the framebuffer for rM2: https://rmkit.dev/news/rm2-status/

In terms of launching without the home button: when we get remux working on rM2, you can slide up the left or right side of the screen to launch it.

**Comment by raisjnn** [comment]
also, congrats on your rM2 (and sorry rmkit isn't working yet - but it is only a matter of time)

**Comment by raisjnn** [comment]
we have succeeded in drawing to framebuffer on rm2 (with help from others) - i think rmkit will be ported reasonably soon.

**Comment by raisjn** [comment]
[made some progress](https://imgur.com/a/02HJJuI) using ddvk/remarkable2-framebuffer rm2fb IPC server. 

current issues:

* screen blanking is not working correctly (this prevents remux from being the best it can be)
* the code for rm2 support is quick hacks that require compiling specifically for rM2, need to actually fix rmkit code to be able to dynamically work on rM1 or rM2
* fast refresh (for drawing with pen) is not working yet
* can't peer into xochitl's memory yet

what works:

* drawing demo
* harmony
* minesweeper
* remux ( has some hiccups with drawing screen, but i can switch between xochitl and harmony and minesweeper correctly)

untested:

* nao package manager
* simple app script

**Comment by raisjn** [comment]
[video of remux + mines + harmony + xochitl](https://imgur.com/gallery/prYASsR)

still having trouble switching back and forth between xochitl and non-xochitl apps, but its only a matter of time.

**Comment by tadfisher** [comment]
I'm trying to get a native framebuffer library going to avoid relying on xochitl, but there are possibly three different panels to support. Can those with a reMarkable 2 run the following in an SSH session, so I can verify that I'm looking in the right place for the panel identifier?

```
dd if=/dev/mmcblk2boot1 bs=1 count=120 | hexdump
```

**Comment by jinnovation** [comment]
@tadfisher: 

```
reMarkable: ~/ dd if=/dev/mmcblk2boot1 bs=1 count=120 | hexdump
0000000 0000 0f00 4d52 3131 2d30 3430 2d33 3231
0000010 3430 0037 0000 460c 4d55 3032 3933 3432
120+0 records in
120+0 records out
0000020 3338 0039 0000 420f 4459 3032 3930 3531
0000030 3030 3232 3433 0000 1900 5545 5a46 5241
0000040 3957 5531 5643 3030 4753 4134 2054 312d
0000050 332e 0030 0000 540a 5345 5354 445f 4e4f
0000060 0045 0000 0000 0000 0000 0000 0000 0000
0000070 0000 0000 0000 0000                    
0000078
```

**Comment by raisjn** [comment]
I like ddvk's solution: use a touch gesture to go from xochitl -> launcher and launcher -> xochitl. When moving between the boundary of launcher / xochitl, the SWTCON has to get restarted, but otherwise it looks pretty smooth.

One downside is that re-starting xochitl will lose your place in it (i think), so I'd like to work towards a solution that will not require restarting xochitl (perhaps just flashing the screen once or twice)

**Comment by tadfisher** [comment]
I've been thinking about replacing /dev/fb0 with a virtual framebuffer managed by a daemon, which could facilitate multitasking in a safe way by locking the device around framebuffer updates. I might be paranoid, but this would also allow for rate-limiting updates to prevent bricking the display.

**Comment by raisjn** [comment]
> I've been thinking about replacing /dev/fb0 with a virtual framebuffer managed by a daemon, which could facilitate multitasking in a safe way by locking the device around framebuffer updates. I might be paranoid, but this would also allow for rate-limiting updates to prevent bricking the display.

sounds interesting. have you looked at [rm2fb's architecture](https://github.com/ddvk/remarkable2-framebuffer/issues/4)? It is also a server model (with a "daemon" managing the framebuffer) and clients interacting with the server through IPC. in the future, we'd like to replace the daemon's FB code with the open source FB code. it would be nice if we (anyone in the rM community) could collaborate here (either on the server model or on the open source SWTCON). 

in term's of the client interaction, we started with an LD_PRELOAD shim for rM1 apps (good idea, @pgaskin!) (which creates a "fake" /dev/fb0 by pretending to be there), but [@pgaskin also suggested a way of making a virtual /dev/fb0 using FUSE](https://github.com/ddvk/remarkable2-framebuffer/issues/11#issuecomment-723304071). there are probably even more ways to create the fake /dev/fb0, but whichever way is taken, i think it's worth pursuing creating a fake /dev/fb0

for batching (it's not paranoid!), i've tried two things:

1) putting large updates in their own thread (didn't work out well)
2) merging all dirty regions into one larger region when emptying the update queue, then running the update. requires keeping track of the highest quality waveform mode used. 

not sure if either were useful, it is hard to tell before we have fast drawing working.

**Comment by pgaskin** [comment]
The FUSE method would be the only way (other than a kernel driver, but then you're basically reinventing the wheel) to support the normal ioctls AFAIK. If the fake /dev/fb0 doesn't support the ioctls, it's arguably worse than the LD_PRELOAD shim (note that it can be directly linked into static binaries if needed) or implementing the IPC directly in applications (which I wouldn't recommend in general, since it'll restrict the changes you can make in the future) since it'll look the same but act differently.

Regarding the LD_PRELOAD shim: I saw your comment about it being ready for review, and I'll be getting around to doing a full review as soon as I have time.

**Comment by raisjn** [comment]
> which could facilitate multitasking in a safe way by locking the device around framebuffer updates.

I think I understand the context a little better now (after re-reading the thread): Would your proposal help with xochitl -> launcher and launcher -> xochitl? Or would it help in general for multi-tasking apps? (or both?). I had wondered about giving each client its own piece of shared memory (so they can't clobber each other) and when they talk to server, their updates come from only their shared mem.

> Regarding the LD_PRELOAD shim: I saw your comment about it being ready for review, and I'll be getting around to doing a full review as soon as I have time.

uh oh - be gentle, please :face_with_head_bandage:

**Comment by raisjn** [comment]
remarkable2 support is now available with [rm2fb](https://github.com/ddvk/remarkable2-framebuffer)

the current binaries on build.rmkit.dev have rm2 support. we'll update this task when the toltec packages land in testing and stable

**Comment by raisjn** [comment]
rmkit apps in toltec testing repo now support rm2. they will be merged into stable in the next merge window

the other piece is finishing the rm2fb PR on toltec. after that, i believe rm2 support will be mostly finished

**Comment by raisjn** [comment]
rm2fb is in toltec stable. all rmkit apps in toltec stable now support rM2 as well, closing out

**Comment by staeff777** [comment]
Sorry, this might be a newbe Question: I installed remux and started the service on my new RM2. How can I open it? Sliding rupward at the sides - as explained above - shows no effect for me.

**Comment by raisjn** [comment]
Do you have rm2fb installed from toltec? You need rm2fb for apps to be able to draw to screen. 

to launch remux: you can swipe up the side of the display. the latest build (0.1.5) will also launch remux when you tap with three fingers, which will hit toltec in a day or two.

**Comment by staeff777** [comment]
Yes, you are right.
Is it possible to set rm2fb as a dependency of the remux package? ( https://openwrt.org/docs/guide-developer/dependencies )

**Comment by Eeems** [comment]
Since toltec is also used by rM1, and rm2fb does not work on the rM1 we aren't going to be doing that. But we are looking into how to ensure that the rM2 always gets rm2fb as a base dependency.
