### ISSUE TITLE
Tearing issue (rm1)

### ISSUE THREAD

**Issue by twitwi** [rmkit-dev/rmkit#36]
I tried rmkit and it seems to be working but the display is highly teared everywhere (I cannot read, but almost, the text in the menu, the animation demo is also teared etc).

I'm not sure if this is a know or frequent issue. I don't if it shares some low level API use, but I tried running https://github.com/LinusCDE/retris and this is not teared.

**Comment by raisjn** [comment]
can you share a screenshot?

**Comment by twitwi** [comment]
Sure, I was installing some VNC server to be able to do it easily.

Firing up the menu
![image](https://user-images.githubusercontent.com/244649/100752766-42708900-33e9-11eb-8fe6-40162a0af7fa.png)

The animation demo
![image](https://user-images.githubusercontent.com/244649/100752844-59af7680-33e9-11eb-9b89-86a14902dd42.png)

**Comment by twitwi** [comment]
It ran from `wget -O- https://rmkit.dev/try.sh -q | sh -` (but I get the same with the install script)

**Comment by raisjn** [comment]
can you try the packages from toltec?

the screenshot looks like what happens if the resolution is wrong :( what is the resolution of your device?

**Comment by twitwi** [comment]
Great, with toltec the menu is clean.

It was at first listing the apps (that were still teared), so I guessed the old apps were being started and removed them.
Can I install rmkit apps from toltec?

Any easy way to get the resolution?

**Comment by raisjn** [comment]
if the toltec apps work, it is likely something wrong in the latest commits.

I'll likely remove the installation instructions and recommend everyone use toltec. (yes, most rmkit apps are in toltec)

you can delete the old apps by removing /home/root/apps

**Comment by twitwi** [comment]
I tried installing harmony using opkg, I got a SIGABRT (and incendently the resolution):

```
reMarkable: ~/ opkg install harmony
Package harmony (0.0.1-16) installed in root is up to date.
reMarkable: ~/ harmony
W: 1408 H: 1920
XRES 1404 YRES 1872 BPP 16 GRAYSCALE 0
W: 1408 H: 1920
CLEANING UP FB
received SIGABRT, exiting
```

**Comment by twitwi** [comment]
Strange...
- I rebooted the remarkable -> tearing again (on the menu),
- I disabled and re-enabled remux -> tearing still,
- I opk uninstalled and opk reinstalled and re-enabled -> menu ok

**Comment by Eeems** [comment]
Maybe double check to make sure there is only one copy of the binaries?

**Comment by twitwi** [comment]
Hum, no duplicates, but the relatively good news is that I rebooted several times and no tearing (at every reboot).
Harmony still SIGABRTs but it is probably a different issue.

**Comment by raisjn** [comment]
harmony sigabrt could be https://github.com/rmkit-dev/rmkit/issues/30

**Comment by raisjn** [comment]
maybe the tearing is some timing issues, where remux reads the resolution before xochitl finishes booting. need to investigate

**Comment by twitwi** [comment]
> harmony sigabrt could be #30

Thanks for the pointer.
I just checked and the folder exists (I also tried removing it, no change) so it seems to be caused by something else.

**Comment by raisjn** [comment]
if the toltec apps work, it is likely something wrong in the latest commits.

I'll likely remove the installation instructions and recommend everyone use
toltec. (yes, most rmkit apps are in toltec)

**Comment by twitwi** [comment]
I'll exhaustively try again and report when I have the remarkable (tomorrow) but here is what I observed:
- from the bash script -> tearing in remux (one thing we don't see in the screenshot is that it is some offset fixed over time (nothing moves on the screen),
- from opk install -> no tearing in remux
- from the bash script -> tearing (but running apps, incl harmony)
- from opk install harmony -> SIGABRT

**Comment by twitwi** [comment]
Here is my report (the first block confirms what I reported earlier) followed by a setting (harmony without remux) that runs but crashes at the second stroke.

```
I cleaned everything, removing all apps (opkg uninstall + rm apps/)

reboot
opkg install remux harmony
systemctl enable --now remux

- remux (menu) ok
- harmony from the menu -> blank white screen
- harmony from the shell -> SIGABRT

reboot (just in case)
-> same behavior

opkg remove remux harmony
reboot

wget -O- https://rmkit.dev/install.sh -q | sh -

- remux shows "teared"
- if I manage to click where I think is harmony -> teared but running harmony

reboot (just in case)
-> same behavior

apps/harmony from the shell -> same (teared but running)
(output)
W: 1404 H: 1872
XRES 1404 YRES 1872 BPP 16 GRAYSCALE 0
W: 1404 H: 1872

opkg install remux harmony

reboot

- menu ok (showing all rmkit apps)
- harmony teared (as well as other rmkit apps)
```

Then (with the opkg version) I tried quite randomly, to start harmony (from the shell) while remux is off (or not even installed) -> harmony fires up unteared

However, the first stroke works and I get

```
reMarkable: ~/ harmony
W: 1408 H: 1920
XRES 1404 YRES 1872 BPP 16 GRAYSCALE 0
W: 1408 H: 1920
ADDING TO UNDO STACK, DIRTY AREA IS 1404 1872 0 0
```

But the next time I touch the screen with the pen, I get `Bus error (core dumped)`.
The core dump also happens when I start drawing after I used the menu to change the brush.

NB: the teared (wget | bash) version of harmony does not crash, allowing me to draw several stroke

**Comment by raisjn** [comment]
can you use strace on the opkg binary and upload the logs? `strace harmony`. my hunch still says it's a missing directory that needs to be created, maybe /home/root/harmony/saved_images. if so, we will see a failed open in the strace logs

if strace isn't on rm, can install it with opkg

I'm sorry you are running until this bad behavior, thanks for taking time to investigate.

just fyi, I'm not able to code much for the next week or two, so don't feel like you need to rush.

**Comment by raisjn** [comment]
also, i don't recommend using the shell installation scripts, so no need to continue investigating those (if you don't want to)

**Comment by raisjn** [comment]
also, if we dont see the issue with strace, we can recompile with debugging symbols and run it with gdb, then print out stack trace - that will give definitive reason for the crash, usually

**Comment by twitwi** [comment]
the folder do exist, and I noticed one more thing: I used the teared-but-working harmony to draw stuff and when I run the unteared (crashing at the second stroke) harmony, it shows the picture that I had drawn... and it is shown **teared** and I can draw (one stroke) non-teared over it.

**Comment by twitwi** [comment]
`strace harmony 2>&1 | tee harmony.strace` (making quick single dot strokes to limit the log size, the second stroke core dumps)
[harmony.strace.txt](https://github.com/rmkit-dev/rmkit/files/5629382/harmony.strace.txt)

**Comment by raisjn** [comment]
interesting. maybe delete and recreate the folder? could be that the tearing version created bad data

**Comment by twitwi** [comment]
We can forget about the tearing if we focus on the opkg version.

I deleted the `~/harmony/` folder, now it crashes on start, trying to load the image (but this would not happen in normal operating conditions):

```
....
stat64("/home/root/harmony/saved_images/fb.0.raw", 0x7ef924e8) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/root/harmony/saved_images/fb.0.raw", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/root/harmony/saved_images/fb.0.raw", O_RDWR) = -1 ENOENT (No such file or directory)
mmap2(NULL, 5406720, PROT_WRITE, MAP_SHARED, -1, 0) = -1 EBADF (Bad file descriptor)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffff} ---
write(2, "CLEANING UP FB", 14CLEANING UP FB)          = 14
write(2, "\n", 1
)                       = 1
ioctl(3, FBIOGET_VSCREENINFO, 0x7ef92188) = 0
ioctl(3, FBIOPUT_VSCREENINFO, 0x7ef92188) = 0
ioctl(0, EVIOCGRAB, 0)                  = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(5, EVIOCGRAB, 0)                  = -1 EINVAL (Invalid argument)
ioctl(4, EVIOCGRAB, 0)                  = -1 EINVAL (Invalid argument)
ioctl(6, EVIOCGRAB, 0)                  = -1 EINVAL (Invalid argument)
write(2, "received SIGABRT, exiting", 25received SIGABRT, exiting) = 25
write(2, "\n", 1
)                       = 1
close(0)                                = 0
close(5)                                = 0
close(4)                                = 0
close(6)                                = 0
exit_group(11)                          = ?
+++ exited with 11 +++
```

**Comment by twitwi** [comment]
I recreate `~/harmony` and `~/harmony/saved_images` (empty), it ran, had no image to resume but was ok with it (just restarting with a blank drawing)

and **it works** (even several strokes)

**Comment by twitwi** [comment]
Thanks a lot, I'll try to reproduce all this (incl. breaking the thing with the script version) to be sure.

**Comment by raisjn** [comment]
sounds good!

phew - thanks for figuring it out! I'll keep this task open until the scripts are removed from the readme.

now that you have toltec installed, you may want to see if there are other apps in there for you ( https://toltec-dev.org/stable/ )

**Comment by twitwi** [comment]
I could reproduce the problem (corrupted raw probably) and the fix:

- install with the script, start harmony (teared) and draw stuff
- remove the apps/
- install via opkg
- start harmony, unteared, but crashes at the second stroke,
- rm harmony/saved_images/fb.0.raw  (NB the harmony/saved_images/ folder must exist for harmony to be ok)
- start harmony, everything is fine!

thanks for these projects!

**Comment by raisjn** [comment]
closing this out since it shouldn't happen any more. (i looked into the commit history and i had a bad commit which was installed from the install script. since only toltec is now in instructions, this should be less possible)
