### ISSUE TITLE
[simple] Make buttons look different than labels

### ISSUE THREAD

**Issue by Eeems** [rmkit-dev/rmkit#37]
Currently a button is just text, which means that it's not clear to the end user that it can be interacted with. Here are some options:

- Black 1px square border around the button
- Black 1px rounded border around the button
- Underline

**Comment by raisjn** [comment]
241e5163b78e9ed75ed7db2d950a540267ea1e46 adds an underline to buttons in simple - the UI is way better with this improvement!

**Comment by Eeems** [comment]
Screenshots?

**Comment by raisjn** [comment]
landed in toltec stable. the underline is a little short (could be one en longer, maybe), so might update it down the line
