### ISSUE TITLE
[harmony] Blank page when starting

### ISSUE THREAD

**Issue by humCopper** [rmkit-dev/rmkit#38]
harmony version: 0.0.1-16

# Issue
When launching harmony, the screen goes blank

# Steps to reproduce
1. install harmony with ```opkg install harmony```
2. open harmony with remux

journalctl output
```Dec 08 23:20:26 reMarkable remux[369]: 20:26.726                          Scanning: false
Dec 08 23:20:35 reMarkable remux[369]: PROC 378 /usr/bin/xochitl
Dec 08 23:20:35 reMarkable remux[369]: --system
Dec 08 23:20:35 reMarkable remux[369]:  378
Dec 08 23:20:35 reMarkable remux[369]: CURRENT APP IS Remarkable
Dec 08 23:20:35 reMarkable remux[369]: current app 0.0176978
Dec 08 23:20:35 reMarkable remux[369]: PROC 378 /usr/bin/xochitl
Dec 08 23:20:35 reMarkable remux[369]: --system
Dec 08 23:20:35 reMarkable remux[369]:  378
Dec 08 23:20:35 reMarkable remux[369]: SENDING 19 TO GROUP -378 RET 0
Dec 08 23:20:35 reMarkable remux[369]: term apps 0.0197499
Dec 08 23:20:35 reMarkable remux[369]: W: 1408 H: 1920
Dec 08 23:20:35 reMarkable remux[369]: SNAPSHOTTING Remarkable
Dec 08 23:20:35 reMarkable remux[369]: No such file or directory
Dec 08 23:20:35 reMarkable remux[369]: RENDERING Remarkable
Dec 08 23:20:48 reMarkable remux[369]: W: 1408 H: 1920
Dec 08 23:20:49 reMarkable remux[369]: RENDERING harmony
Dec 08 23:20:49 reMarkable remux[369]: LAUNCHING APP harmony
Dec 08 23:20:49 reMarkable remux[369]: CHECKING PROCESS harmony
Dec 08 23:20:49 reMarkable remux[369]: RENDERING harmony
Dec 08 23:20:49 reMarkable remux[369]: W: 1408 H: 1920
Dec 08 23:20:49 reMarkable remux[369]: XRES 1404 YRES 1872 BPP 16 GRAYSCALE 0
Dec 08 23:20:49 reMarkable remux[369]: W: 1408 H: 1920
Dec 08 23:20:49 reMarkable remux[369]: CLEANING UP FB
Dec 08 23:20:49 reMarkable remux[369]: received SIGABRT, exiting
```

**Comment by Eeems** [comment]
What device is this on? rM1 or rM2?

**Comment by humCopper** [comment]
rM1

**Comment by raisjn** [comment]
how did you install? toltec?

**Comment by Eeems** [comment]
> 
> 
> how did you install? toltec?

See the steps to reproduce, it was from toltec

**Comment by raisjn** [comment]
what happens if you launch harmony directly? and can you screenshot the blank screen?

**Comment by humCopper** [comment]
Output from launching harmony directly
```
reMarkable: ~/ /opt/bin/harmony 
W: 1408 H: 1920
XRES 1404 YRES 1872 BPP 16 GRAYSCALE 0
W: 1408 H: 1920
CLEANING UP FB
received SIGABRT, exiting
```

Screen shot:
![fb](https://user-images.githubusercontent.com/35010945/101698253-cdcbc900-3a3e-11eb-869e-3819780a29fd.png)
End screen shot

**Comment by raisjn** [comment]
thank you!

can you share strace output and verify that /home/root/harmony and
/home/root/harmomy/saved_images exists?

**Comment by humCopper** [comment]
[harmony_strace.txt](https://github.com/rmkit-dev/rmkit/files/5669506/harmony_strace.txt)

/home/root/harmony exists
/home/root/harmomy/saved_images does not

**Comment by humCopper** [comment]
I made /home/root/harmomy/saved_images, now it works.

**Comment by raisjn** [comment]
this one bug has come back to bite me who knows how many times :-( the toltec package used to automatically create that directory, maybe i'll try to add that back

**Comment by raisjn** [comment]
(added code back to toltec for creating this directory)
