### ISSUE TITLE
Help with drawing in grayscale

### ISSUE THREAD

**Issue by mrichards42** [rmkit-dev/rmkit#40]
Thanks for a great project! I'm hoping you can help me understand the color drawing apis a little better (apologies for the wall of text):

I'm trying to write an app that will to draw in grayscale, ideally as many shades as possible. From what I can tell, most of the standard Framebuffer methods only support drawing using the predefined WHITE, BLACK, GRAY, RUBBER, and ERASER colors (e.g. [draw_rect()](https://github.com/rmkit-dev/rmkit/blob/d03ef4e140c432bbf1d1bfacb0d3159c13d9cc04/src/rmkit/fb/fb.cpy#L239)), although looking at the implementation, even GRAY is done by dithering, and individual pixels are only set to WHITE or BLACK.

I've had some success converting arbitrary colors using [to_rgb565()](https://github.com/rmkit-dev/rmkit/blob/d03ef4e140c432bbf1d1bfacb0d3159c13d9cc04/src/rmkit/fb/fb.cpy#L269-L273) and I can see the colors are set correctly by examining `fbmem`, but I've had trouble getting anything to draw on the screen itself unless I use WHITE, BLACK, or GRAY. It seems like it might be an issue with refreshing? I've noticed that I'll see a flash of the image I've drawn, followed by a white screen . . . I can sometimes get the image to show up afterwards but it's inconsistent enough that I'm not sure what causes the image actually end up getting rendered on the screen.

I think I've managed to track it down to the `waveform_mode`. I can draw in grayscale and have it rendered to the screen if I set `waveform_mode = WAVEFORM_MODE_GC16` (which I got from looking at both [remux](https://github.com/rmkit-dev/rmkit/blob/d03ef4e140c432bbf1d1bfacb0d3159c13d9cc04/src/remux/launcher.cpy#L112) and [Framebuffer::load_from_png()](https://github.com/rmkit-dev/rmkit/blob/d03ef4e140c432bbf1d1bfacb0d3159c13d9cc04/src/rmkit/fb/fb.cpy#L397)).  I don't exactly understand what the different waveform modes do, but I assume setting GC16 all the time isn't ideal (it's slower?), since Framebuffer [resets waveform_mode](https://github.com/rmkit-dev/rmkit/blob/d03ef4e140c432bbf1d1bfacb0d3159c13d9cc04/src/rmkit/fb/fb.cpy#L600) after each draw.

Is there a practical way to draw in grayscale all the time? Any tips? Thanks!

**Comment by raisjn** [comment]
yes, everything you said is right. 

a document that gives more info on the waveform modes is https://www.waveshare.com/w/upload/c/c4/E-paper-mode-declaration.pdf

DU = can draw white or black pixels and is the fastest, this is why GRAY is dithered. its used for drawing with low latency
GC16 = can draw high quality and is likely the slowest 
AUTO = tries to pick appropriate mode to use based on whats being displayed

can look in mxcfb.h for more waveforms likely (or see if there are some in libremarkable)

one way to always draw in high quality would be to reset the fb's waveform mode on each iteration of the main loop before calling ui::MainLoop::redraw(). or you can set the waveform mode when you are first drawing a grayscale pixel, at that point can upgrade the waveform mode to higher quality.

**Comment by mrichards42** [comment]
Thanks, and especially thanks for the pointer to the waveform modes document, that's extremely helpful.
