### ISSUE TITLE
[remux] Toggle between apps

### ISSUE THREAD

**Issue by ludovico** [rmkit-dev/rmkit#41]
I'm using ddvk's Remarkable-hacks, where you can toggle between the two most recent documents with a two-finger downward swipe. This is great for reading pdf's while also taking notes in another document.

If something similar is possible with remux, I could read on Plato or KOReader - which are much better than xochitl for EPUB files - while still taking notes the normal way.

**Comment by raisjn** [comment]
this is such a great idea, thank you!

one thing is what gesture to bind it to (three finger swipe down? four finger tap?), so as part of this, i might make a simple remux config file

**Comment by ludovico** [comment]
I think three finger swipe makes sense, but a config file would be awesome

**Comment by danshick** [comment]
Is there some plan to move all remux gestures to genie at some point? It'd be nice to configure gestures in a single place to avoid overlap. Idk, haven't thought this out much and definitely off topic for this issue.

**Comment by raisjn** [comment]
@danshick this is a great question!

my thought is to make a couple gestures configurable through remux.conf (if want to move away from defaults). as well as make whatever actions are available through gestures are available through a simple CLI invocation. then people can disable the gestures via the config and connect them through genie (or any other app)

**Comment by ludovico** [comment]
@danshick that would be great!

If we were able to invoke any action through the CLI, implementing this feature should be possible through a simple shell script. My C++ skills are nowhere near good enough, but I would be happy to help if there is anything else 👍

**Comment by raisjn** [comment]
in terms of bringing this into remux, the path forward will be:

* [x] add switch to last app command to remux
* [ ] add API server to remux
* [ ] connect API to remux commands
* [ ] add API client binary for invoking 'pause', 'resume', 'switch to last app', 'launch'

after that, 

* [ ] add remux.conf file with ability to disable (maybe configure) built in gestures

**Comment by raisjn** [comment]
https://github.com/rmkit-dev/rmkit/commit/5cc49f45f74d59057af18b520cfcd909bd00bb9f adds a FIFO API to remux. it creates `/tmp/remux.api` which accepts newline delimited commands.

so far, the commands are: `show`, `hide` and `back` (back will swap between last two apps)

as usual, binaries are available on build.rmkit.dev/master/latest and will be available in toltec stable in a week or two

**Comment by Eeems** [comment]
I wonder if there is a better location than `/tmp` for that. Maybe `/var/volatile` or something in `/run`/`/var/run`

**Comment by danshick** [comment]
> I wonder if there is a better location than `/tmp` for that. Maybe `/var/volatile` or something in `/run`/`/var/run`

For reference, my compositor Sway keeps that in `/run/user/1000/sway-ipc.1000.2597570.sock`. Also of note, the .sock extension makes it clearer what this file is.

**Comment by raisjn** [comment]
thanks for the pointers!

as an API, i want it to be in a simple to explain location so that scripts can say `echo show > /path/to/remux/api`. I wasn't sure whether to keep fifo in the name vs. .api since fifo is an implementation detail and i wanted the shell command above to have some semantic meaning (vs impl. meaning). i'm leaning to `/run/remux.api` (since it's so short)

**Comment by raisjn** [comment]
k, added remux.conf in the latest commits, documented how to use the API and the .conf settins in https://github.com/rmkit-dev/rmkit/tree/master/src/remux

i think the gesture engine can use some work (especially around swipes), but now you can configure either through remux.conf and the new settings or can disable the gestures in remux altogether and use a separate gesture engine. 

the API should hit toltec stable in next merge, then remux.conf will be in mege after that. otherwise, can always get the latest binaries from build.rmkit.dev/master/latest (especially if want to give feedback or help test)

**Comment by ludovico** [comment]
@raisjn tested it now, it works perfectly. The switch between apps is actually much quicker than the switch between documents in xochitl. Will keep playing around with it. 

It's all I could have wanted, thank you so much! 

BTW, happy to close it now, but it looks like you do that yourself to keep track. Feel free to correct me :slightly_smiling_face:

**Comment by ludovico** [comment]
Did notice one thing: When you start remux, you have to go switch apps two times before the toggle works. I guess it could work to add xochitl as the initial 'last app' entry. 🤔

**Comment by raisjn** [comment]
thanks! pushed a fix that does that, I'll likely close after this lands in toltec stable

**Comment by ludovico** [comment]
Nice! Works great 👍

**Comment by raisjn** [comment]
available in stable (through genie), closing for now. the configurable remux is in testing (and will land in stable in the next merge)
