### ISSUE TITLE
[rmkit] incomplete touch events while dragging

### ISSUE THREAD

**Issue by mrichards42** [rmkit-dev/rmkit#45]
My setup: rmkit master (a8ded6b); rm2 with rm2fb in toltec-testing

I noticed a widget was getting a lot of mouse_down events. It seemed like I got a down when I started a touch, but also every time I dragged (without lifting my finger off the screen). Further investigation revealed that the widget was getting a sequence of events like so: down,leave,down,leave,down ...

The attached [events.log](https://github.com/rmkit-dev/rmkit/files/5815474/events.log) has a full log of one session with `#define DEBUG_INPUT_EVENT 1`. I'm no expert in decoding these events, but based on the log it looks like what's happening is that the initial touch (down) event starts with `ABS_MT_TRACKING_ID`, then gets full position, pressure, etc. info, but subsequent motion events are produced as deltas (i.e. position or pressure change), not as full events. So those motion events are being processed with uninitialized values. In the case of a motion event that doesn't include both X and Y coords, one of those values is way off screen, leading to the extra `leave` event.

**Comment by raisjn** [comment]
thank you for opening! this looks like a bug indeed (i tried it on simple example) :-/ will investigate and fix. does the mouse_enter / mouse_leave events work any better? 

i just compiled and tried out puzzles, very very cool!

**Comment by raisjn** [comment]
(also, it really makes my day to see your repo)

**Comment by raisjn** [comment]
I think 7560d2556d18af2848c30ad9f323dc46a78829d0 will fix this - now touch events have their .x and .y pulled from the previous event if it wasn't yet set

**Comment by mrichards42** [comment]
Thanks, that fix is perfect! Glad to hear you were able to compile the code and try it out. It's been fun to write so far.
