### ISSUE TITLE
[rmkit] proposal: widget styles

### ISSUE THREAD

**Issue by mrichards42** [rmkit-dev/rmkit#50]
This isn't fully thought out yet, just looking to start a discussion.

I'm finding that most of the widgets I've tried work well, but I often want to make small tweaks (e.g. [OutlineButton](https://github.com/mrichards42/remarkable_puzzles/blob/49eb1ba79073a8248ec0d49657af892acaebaab6/src/main.cpp#L78-L93), which draws a 1px border and vertically centers the text). In the case of buttons, I think those are actually good defaults, and I'd be happy if all buttons were centered and had a border. But I could also see wanting to vertically center any kind of text-based widget, and I could see wanting to put a border around any kind of widget (even if just for debugging purposes).

So that got me thinking about the more general idea of styles. Widgets already support a fair amount of customization, like `ui::Text` supports `font_size` and `underline`, but not all text-based widgets support those, e.g. `ui::Button` doesn't support `font_size`, and `ui::DropdownButton` doesn't support either one. There are really two problems I'm trying to solve with this idea:

1. Discoverability -- it's a little tricky to find all the configurable variables in each class without reading a lot of the source. If each had a `style` variable, or a `set_style` function, it would make that part easier.
2. Consistency -- widgets that _use_ other widgets without subclassing them (like ui::Button) should probably pass styles on to their children . . . so if you set the button's font_size for instance, that also sets the ui::Text widget's font size. Making `style` a single bitmask or a struct with a few fields would make it easy to passing around, and it would also open the door to setting style in the constructor.

**Prior art**

I see Qt has css-like stylesheets, which seems pretty cool, but also way overboard for rmkit, at least currently. I've used wxWidgets a good bit in the past, which has a simpler concept of styles: each [wxWindow](https://docs.wxwidgets.org/trunk/classwx_window.html)-derived class has a font, a border, a background, and a style bitmask (border style, background style, scrollbar style, etc). Some subclasses add more bits to the mask, like [wxStaticText](https://docs.wxwidgets.org/trunk/classwx_static_text.html) and [wxButton](https://docs.wxwidgets.org/trunk/classwx_button.html) have alignment bitmasks, and [wxTextCtrl](https://docs.wxwidgets.org/trunk/classwx_text_ctrl.html) has all kinds of style flags, like readonly, password, multiline, wrapping.

**Comment by raisjn** [comment]
i think this is a great idea!

**Comment by raisjn** [comment]
some styles i see so far are:

* font size
* underline
* justify
* vertical align (not impl. in rmkit yet
* x / y padding (used in buttons)

they all seem relevant to text (even though x/y padding is used in the button). can probably use a struct or class here to represent these options and pass them around
