### ISSUE TITLE
Should Stylesheet functions return a copy?

### ISSUE THREAD

**Issue by mrichards42** [rmkit-dev/rmkit#57]
I wrote ui::Stylesheet so that all its functions [mutate the stylesheet and return a reference to `*this`](https://github.com/rmkit-dev/rmkit/blob/1fdc7b2b2ca1b8983093157e3db5f989e4977931/src/rmkit/ui/style.h#L72-L77) for efficiency when chaining, but I realize now that might be more complicated than its worth. For instance [this diff](https://github.com/rmkit-dev/rmkit/commit/494332c7b4d2bbf025a10d8e39660d2388d6239b) doesn't just apply the stylesheet to a single button, it actually changes the global Button::DEFAULT_STYLE.

The pattern of taking an existing Stylesheet and applying a new one on top of it makes a lot of sense to me, so I wonder if it might be better to go ahead and have all the builders return a copy.

**Comment by raisjn** [comment]
i didn't even realize i was changing the default style, oops!

yeah, let's go with the copy route and see what falls out from it
