### ISSUE TITLE
[remux] Automatically suspending after 5 minutes

### ISSUE THREAD

**Issue by jdigi78** [rmkit-dev/rmkit#80]
Remux is causing my tablet to suspend way sooner than the 20 minutes set in xochitl. There should be a way to disable this because it causes my sleep screen to display incorrectly.

**Comment by jonahweissman** [comment]
You can fix this by setting `IdleSuspendDelay` in the xochitl config. See https://github.com/rmkit-dev/rmkit/issues/54#issuecomment-763662122 for more details

**Comment by jdigi78** [comment]
> setting `IdleSuspendDelay` in the xochitl config

This is set to 20 minutes, the issue is remux is not respecting that setting and suspending in much shorter time

**Comment by raisjn** [comment]
thank you for the suggestion!

http://raisjn.net/remux.no_suspend can be used for now to get a remux binary that won't do power management. long term, there will be a config option added to remux.conf for telling remux not to manager power. 

> This is set to 20 minutes, the issue is remux is not respecting that setting and suspending in much shorter time

this shouldn't be the case. its likely that the setting was changed when toggling it in xochitl and remux wasn't restarted.

**Comment by raisjn** [comment]
addressed in https://github.com/rmkit-dev/rmkit/commit/aa5ef055babb3e191f8feb8c7f427fddbd3626ed

**Comment by raisjn** [comment]
this is now in toltec testing and should be included in the next stable merge
