### ISSUE TITLE
[build] DOCKER_APPS recipe does not work

### ISSUE THREAD

**Issue by jonahweissman** [rmkit-dev/rmkit#81]
`make remux_docker` fails:
```
bash: scripts/build/docker_build.sh: No such file or directory
```
It seems like that file didn't exist at the time of [the first commit that mentions it](https://github.com/rmkit-dev/rmkit/commit/600d6513d09dadd5af4cc19c4afb274777ae2278). Maybe just delete the DOCKER_APPS recipe and documentation from the Makefile? It doesn't seem like anyone is using this feature, but it has the potential to confuse people.

**Comment by raisjn** [comment]
thanks for reporting! 5799a497ae153df837965fea4c7873f55a10a98f

**Comment by jonahweissman** [comment]
Works for me! Thank you
