### ISSUE TITLE
[Lamp] How to

### ISSUE THREAD

**Issue by Pemo11235** [rmkit-dev/rmkit#83]
Can you explain how to install and use  Lamp? 
It possible to draw figure giving as input coordinates with a .json?
Sorry for this dummy post but I tried, and I can't figure it out alone. 
Thanks

**Comment by raisjn** [comment]
copy it to your remarkable to install. it takes input on stdin in the format in the README. so once you run the program, you can then type different commands to see what happens. 

`pen rectangle 500 500 1000 1000` draws a rectangle. press ctrl-c to exit. if you want to draw multiple things at once (and save them for later use), you can make a new file, like 

```
# example.input
pen circle 500 1000 200 200
pen rectangle 500 500 1000 1000
```

then run the file with `lamp < example.input`. if you are on rM2, make sure to run `rm2fb-client lamp` or `rm2fb-client lamp < input.txt`. 


you can also switch pages using `swipe left` or `swipe right`. currently, the `circle` command requires 4 variables (`x y r1 _`) where `_` doesn't do anything. 

if you want to draw a figure using particular coordinates, you would use `pen down`, `pen move X Y` and `pen up` commands. internally, drawing a rectangle (or other figures) use these three commands.

**Comment by raisjn** [comment]
i'll close this task out for now, but if you build some lamp stuff, i'd be interested to see!

someone else shared this program with me and said: "give it a try on xochtil on a empy note page. and without spoiler, you need the menu to be open"


```
pen circle 500 500 25 50
pen line 10 600 10 600
pen circle 530 530 25 50
pen line 10 600 10 600
pen circle 560 560 25 50
pen line 10 600 10 600
pen circle 590 590 25 50
pen line 10 600 10 600
pen circle 620 620 25 50
pen line 10 600 10 600
pen circle 500 500 5 50
pen line 10 600 10 600
pen circle 470 530 5 50
pen line 10 600 10 600
pen circle 440 560 5 50
pen line 10 600 10 600
pen circle 410 590 5 50
pen line 10 600 10 600
pen circle 380 620 5 50
pen line 10 600 10 600
pen circle 500 500 50 50
pen line 10 600 10 600
pen circle 530 470 50 50
pen line 10 600 10 600
pen circle 560 440 50 50
pen line 10 600 10 600
pen circle 590 410 50 50
pen line 10 600 10 600
pen circle 620 380 50 50
pen line 10 600 10 600
pen circle 500 500 150 50
pen line 10 600 10 600
pen circle 470 470 150 50
pen line 10 600 10 600
pen circle 440 440 150 50
pen line 10 600 10 600
pen circle 410 410 150 50
pen line 10 600 10 600
pen circle 380 380 150 50
pen line 10 600 10 600
```

**Comment by Pemo11235** [comment]
Good news, I make it works and I'm working on a small Java program that allows to draw almost any .SVG.

How?
1. Pick a .SVG.
2. Get a .json with XY coordinates from [Coordinator](https://spotify.github.io/coordinator/)
3. Parse JSON , clean it up and write the input file for lamp.

I'm working on merging intervals atm. 
Infact drawing point-by-point (pen line 1 px long, like _pen line 300 252 301 253_) is kinda slow, and drawing point-to-point (pen down XY, pen move XY, pen up) it should be a lot faster. 
I'm trying to figure out how.

I attached a _star_ example. 
Lemme know, and thanks for your help mate !

[output.txt](https://github.com/rmkit-dev/rmkit/files/5938728/output.txt)

**Comment by raisjn** [comment]
yes, you can do `pen move a b c d` instead of `pen line a b  c d` and it should speed things up. also using `fastpen` instead of `pen` will speed up a little.

but the most efficient speedup will be merging the points that all fall on the same line. using one command per point is inefficient, you can compare tracing the same star with the full lines, should be much faster. 

if you delete 50% of lines (delete every other line, for example), it will speed up by 2x and look a little worse. if you delete 75% of lines, it will speed up even more.
