### ISSUE TITLE
Inproving the readme, make it easy for beginners

### ISSUE THREAD

**Issue by espoirMur** [rmkit-dev/rmkit#94]
First thanks a lot for these tools, thanks for the hard work you have put into this.. 

So I installed the application using this [guide](https://rmkit.dev/apps/remux) , but when I came to the guide I aheve trouble adding an application to the launcher...

In this section on the readme: 

1. via code configuration - edit config.launcher.cpy 
_Where is the configuration file after installing the application binary?_
2. add a binary to the remux watch dir on the remarkable: 
_What is the path of the remux watch dir on the remarkble?_
3. using draft remarkable configuration files

I think if we find the answer to those questions we can see how to improve the readme to make those steps easier for nobs and beginners like me...

**Comment by raisjn** [comment]
you can put a binary in /home/root/apps and remux should list it. make sure it is chmod +x

you can put a draft file in /opt/etc/draft (see draft files in this repo for examples of the spec, which is shared across launchers). remux scans a few directories, please look at code to see which.

usually, most people install toltec (toltec-dev.org) and the apps in toltec all use draft format and are installed into /opt/etc/draft

**Comment by espoirMur** [comment]
Cool... 

Thanks for that @raisjn

**Comment by espoirMur** [comment]
Thanks, the toltec works like a charm..

**Comment by espoirMur** [comment]
But I think the readme can be improved...

**Comment by raisjn** [comment]
please open a PR? :-D otherwise, i'll get to it within the next week

**Comment by espoirMur** [comment]
If I had the answer to those questions at the begin I could open a Pr, but I will try to fire something later today.

**Comment by raisjn** [comment]
a0c2daad97afb15b2bfeeba65b647f246c0c7372 fixes this
